// This file was generated by Examples/Rust/src/generate_main.py

use crate::examples::*;

mod examples;
mod helpers;

fn main() {
    println!("Select example");
    println!("A. bluetooth_connection.rs");
    println!("B. commands.rs");
    println!("C. data_logger.rs");
    println!("D. file_connection.rs");
    println!("E. file_converter.rs");
    println!("F. get_port_names.rs");
    println!("G. keep_open.rs");
    println!("H. network_announcement.rs");
    println!("I. open_async.rs");
    println!("J. ping.rs");
    println!("K. port_scanner.rs");
    println!("L. serial_connection.rs");
    println!("M. tcp_connection.rs");
    println!("N. udp_connection.rs");
    println!("O. usb_connection.rs");

    match helpers::get_key() {
        'A' => bluetooth_connection::run(),
        'B' => commands::run(),
        'C' => data_logger::run(),
        'D' => file_connection::run(),
        'E' => file_converter::run(),
        'F' => get_port_names::run(),
        'G' => keep_open::run(),
        'H' => network_announcement::run(),
        'I' => open_async::run(),
        'J' => ping::run(),
        'K' => port_scanner::run(),
        'L' => serial_connection::run(),
        'M' => tcp_connection::run(),
        'N' => udp_connection::run(),
        'O' => usb_connection::run(),
        _ => {}
    }
}
