import re
import sys
from itertools import dropwhile, takewhile
from pathlib import Path


def top_level_file() -> str:
    main_path = Path(sys.modules["__main__"].__file__).resolve()
    this_directory = Path(__file__).resolve().parent

    return main_path.relative_to(this_directory).as_posix()


def preamble() -> str:
    return f"// This file was generated by {top_level_file()}\n\n"


def split_words(string: str) -> list[str]:
    return re.sub("[^0-9a-zA-Z]", " ", string).split()


def camel_case(string: str) -> str:
    return "".join(w.lower() if i == 0 else w.capitalize() for i, w in enumerate(split_words(string)))


def macro_case(string: str) -> str:
    return re.sub("[^0-9a-zA-Z]", " ", string).upper().replace(" ", "_")


def pascal_case(string: str) -> str:
    return "".join(w.lower().capitalize() for w in split_words(string))


def snake_case(string: str) -> str:
    return "_".join([w.lower() for w in split_words(string)])


def title_case(string: str) -> str:
    return " ".join(w[0].upper() + w[1:] for w in string.split())


def replace(string: str, replacements: tuple[tuple[str, str]]) -> str:
    for old, new in replacements:
        string = string.replace(old, new)

    return string


def insert(path: Path, id: int, code: str) -> None:
    lines = path.read_text().splitlines(keepends=True)

    start_key = f"// Start of code block #{id} generated by {top_level_file()}\n"
    end_key = f"// End of code block #{id} generated by {top_level_file()}\n"

    if all(start_key not in l for l in lines):
        raise Exception(f"Error: Cannot find {start_key.strip()} in {path}")

    if all(end_key not in l for l in lines):
        raise Exception(f"Error: Cannot find {end_key.strip()} in {path}")

    lines_before_start = list(takewhile(lambda l: not l.lstrip().startswith(start_key), lines))

    lines_before_start.append(next(l for l in lines if start_key in l))

    lines_after_end = list(dropwhile(lambda l: not l.lstrip().startswith(end_key), lines))

    content = "".join(lines_before_start)
    if code.endswith("\n\n"):
        content += "\n"
    content += code
    content += "".join(lines_after_end)

    path.write_text(content)
