import os
import re
import sys
from itertools import dropwhile, takewhile


def top_level_file() -> str:
    main_path = os.path.realpath(sys.modules["__main__"].__file__)
    this_directory = os.path.dirname(os.path.realpath(__file__))

    return os.path.relpath(main_path, this_directory).replace("\\", "/")


def preamble() -> str:
    return f"// This file was generated by {top_level_file()}\n\n"


def split_words(string: str) -> list[str]:
    return re.sub("[^0-9a-zA-Z]", " ", string).split()


def camel_case(string: str) -> str:
    return "".join(w.lower() if i == 0 else w.capitalize() for i, w in enumerate(split_words(string)))


def macro_case(string: str) -> str:
    return re.sub("[^0-9a-zA-Z]", " ", string).upper().replace(" ", "_")


def pascal_case(string: str) -> str:
    return "".join(w.lower().capitalize() for w in split_words(string))


def snake_case(string: str) -> str:
    return "_".join([w.lower() for w in split_words(string)])


def title_case(string: str) -> str:
    return " ".join(w[0].upper() + w[1:] for w in string.split())


def replace(string: str, replacements: tuple[tuple[str, str]]) -> str:
    for old, new in replacements:
        string = string.replace(old, new)

    return string


def insert(path: str, id: int, code: str) -> None:
    with open(path) as file:
        lines = file.readlines()

    start_key = f"// Start of code block #{id} generated by {top_level_file()}\n"
    end_key = f"// End of code block #{id} generated by {top_level_file()}\n"

    if all(start_key not in l for l in lines):
        raise Exception(f"Error: Cannot find {start_key.strip()} in {path}")

    if all(end_key not in l for l in lines):
        raise Exception(f"Error: Cannot find {end_key.strip()} in {path}")

    lines_before_start = list(takewhile(lambda l: not l.lstrip().startswith(start_key), lines))

    lines_before_start.append(next(l for l in lines if start_key in l))

    lines_after_end = list(dropwhile(lambda l: not l.lstrip().startswith(end_key), lines))

    with open(path, "w") as file:
        for line in lines_before_start:
            file.write(line)

        if code.endswith("\n\n"):
            file.write("\n")

        file.write(code)

        for line in lines_after_end:
            file.write(line)
