#ifndef DATA_MESSAGES_H
#define DATA_MESSAGES_H

// Start of code block #0 generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py
#include "InertialMessage.h"
#include "MagnetometerMessage.h"
#include "QuaternionMessage.h"
#include "RotationMatrixMessage.h"
#include "EulerAnglesMessage.h"
#include "LinearAccelerationMessage.h"
#include "EarthAccelerationMessage.h"
#include "AhrsStatusMessage.h"
#include "HighGAccelerometerMessage.h"
#include "TemperatureMessage.h"
#include "BatteryMessage.h"
#include "RssiMessage.h"
#include "SerialAccessoryMessage.h"
#include "NotificationMessage.h"
#include "ErrorMessage.h"
// End of code block #0 generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

PyObject* quaternion_message_to_euler_angles_message(QuaternionMessage* self, PyObject* args)
{
    const XIMU3_EulerAnglesMessage message = XIMU3_quaternion_message_to_euler_angles_message(self->message);
    return euler_angles_message_from(&message);
}

PyObject* rotation_matrix_message_to_euler_angles_message(RotationMatrixMessage* self, PyObject* args)
{
    const XIMU3_EulerAnglesMessage message = XIMU3_rotation_matrix_message_to_euler_angles_message(self->message);
    return euler_angles_message_from(&message);
}

PyObject* euler_angles_message_to_quaternion_message(EulerAnglesMessage* self, PyObject* args)
{
    const XIMU3_QuaternionMessage message = XIMU3_euler_angles_message_to_quaternion_message(self->message);
    return quaternion_message_from(&message);
}

PyObject* linear_acceleration_message_to_euler_angles_message(LinearAccelerationMessage* self, PyObject* args)
{
    const XIMU3_EulerAnglesMessage message = XIMU3_linear_acceleration_message_to_euler_angles_message(self->message);
    return euler_angles_message_from(&message);
}

PyObject* earth_acceleration_message_to_euler_angles_message(EarthAccelerationMessage* self, PyObject* args)
{
    const XIMU3_EulerAnglesMessage message = XIMU3_earth_acceleration_message_to_euler_angles_message(self->message);
    return euler_angles_message_from(&message);
}

#endif
