// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef EARTH_ACCELERATION_MESSAGE_H
#define EARTH_ACCELERATION_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct
{
    PyObject_HEAD
    XIMU3_EarthAccelerationMessage message;
} EarthAccelerationMessage;

static void earth_acceleration_message_free(EarthAccelerationMessage* self)
{
    Py_TYPE(self)->tp_free(self);
}

static PyObject* earth_acceleration_message_get_timestamp(EarthAccelerationMessage* self)
{
    return Py_BuildValue("K", self->message.timestamp);
}

static PyObject* earth_acceleration_message_get_w_element(EarthAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.w_element);
}

static PyObject* earth_acceleration_message_get_x_element(EarthAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.x_element);
}

static PyObject* earth_acceleration_message_get_y_element(EarthAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.y_element);
}

static PyObject* earth_acceleration_message_get_z_element(EarthAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.z_element);
}

static PyObject* earth_acceleration_message_get_x_axis(EarthAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.x_axis);
}

static PyObject* earth_acceleration_message_get_y_axis(EarthAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.y_axis);
}

static PyObject* earth_acceleration_message_get_z_axis(EarthAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.z_axis);
}

static PyObject* earth_acceleration_message_to_string(EarthAccelerationMessage* self, PyObject* args)
{
    return Py_BuildValue("s", XIMU3_earth_acceleration_message_to_string(self->message));
}

static PyGetSetDef earth_acceleration_message_get_set[] = {
        { "timestamp", (getter) earth_acceleration_message_get_timestamp, NULL, "", NULL },
        { "w_element", (getter) earth_acceleration_message_get_w_element, NULL, "", NULL },
        { "x_element", (getter) earth_acceleration_message_get_x_element, NULL, "", NULL },
        { "y_element", (getter) earth_acceleration_message_get_y_element, NULL, "", NULL },
        { "z_element", (getter) earth_acceleration_message_get_z_element, NULL, "", NULL },
        { "x_axis",    (getter) earth_acceleration_message_get_x_axis,    NULL, "", NULL },
        { "y_axis",    (getter) earth_acceleration_message_get_y_axis,    NULL, "", NULL },
        { "z_axis",    (getter) earth_acceleration_message_get_z_axis,    NULL, "", NULL },
        { NULL }  /* sentinel */
};

static PyMethodDef earth_acceleration_message_methods[] = {
        { "to_string", (PyCFunction) earth_acceleration_message_to_string, METH_NOARGS, "" },
        { NULL } /* sentinel */
};

static PyTypeObject earth_acceleration_message_object = {
        PyVarObject_HEAD_INIT(NULL, 0)
        .tp_name = "ximu3.EarthAccelerationMessage",
        .tp_basicsize = sizeof(EarthAccelerationMessage),
        .tp_dealloc = (destructor) earth_acceleration_message_free,
        .tp_getset = earth_acceleration_message_get_set,
        .tp_methods = earth_acceleration_message_methods,
};

static PyObject* earth_acceleration_message_from(const XIMU3_EarthAccelerationMessage* const message)
{
    EarthAccelerationMessage* const self = (EarthAccelerationMessage*) earth_acceleration_message_object.tp_alloc(&earth_acceleration_message_object, 0);
    self->message = *message;
    return (PyObject*) self;
}

static void earth_acceleration_message_callback(XIMU3_EarthAccelerationMessage data, void* context)
{
    const PyGILState_STATE state = PyGILState_Ensure();

    PyObject* const object = earth_acceleration_message_from(&data);
    PyObject* const tuple = Py_BuildValue("(O)", object);
    Py_DECREF(PyObject_CallObject((PyObject*) context, tuple));
    Py_DECREF(tuple);
    Py_DECREF(object);

    PyGILState_Release(state);
}

#endif
