// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef ERROR_MESSAGE_H
#define ERROR_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct
{
    PyObject_HEAD
    XIMU3_ErrorMessage message;
} ErrorMessage;

static void error_message_free(ErrorMessage* self)
{
    Py_TYPE(self)->tp_free(self);
}

PyObject* error_message_get_timestamp(ErrorMessage* self, PyObject* args)
{
    return Py_BuildValue("K", self->message.timestamp);
}

PyObject* error_message_get_string(ErrorMessage* self, PyObject* args)
{
    return Py_BuildValue("s", self->message.char_array);
}

PyObject* error_message_get_bytes(ErrorMessage* self, PyObject* args)
{
    return PyByteArray_FromStringAndSize(self->message.char_array, self->message.number_of_bytes);
}

static PyObject* error_message_to_string(ErrorMessage* self, PyObject* args)
{
    return Py_BuildValue("s", XIMU3_error_message_to_string(self->message));
}

static PyGetSetDef error_message_get_set[] = {
        { "timestamp", (getter) error_message_get_timestamp, NULL, "", NULL },
        { "string",    (getter) error_message_get_string,    NULL, "", NULL },
        { "bytes",     (getter) error_message_get_bytes,     NULL, "", NULL },
        { NULL }  /* sentinel */
};

static PyMethodDef error_message_methods[] = {
        { "to_string", (PyCFunction) error_message_to_string, METH_NOARGS, "" },
        { NULL } /* sentinel */
};

static PyTypeObject error_message_object = {
        PyVarObject_HEAD_INIT(NULL, 0)
        .tp_name = "ximu3.ErrorMessage",
        .tp_basicsize = sizeof(ErrorMessage),
        .tp_dealloc = (destructor) error_message_free,
        .tp_getset = error_message_get_set,
        .tp_methods = error_message_methods,
};

static PyObject* error_message_from(const XIMU3_ErrorMessage* const message)
{
    ErrorMessage* const self = (ErrorMessage*) error_message_object.tp_alloc(&error_message_object, 0);
    self->message = *message;
    return (PyObject*) self;
}

static void error_message_callback(XIMU3_ErrorMessage data, void* context)
{
    const PyGILState_STATE state = PyGILState_Ensure();

    PyObject* const object = error_message_from(&data);
    PyObject* const tuple = Py_BuildValue("(O)", object);
    Py_DECREF(PyObject_CallObject((PyObject*) context, tuple));
    Py_DECREF(tuple);
    Py_DECREF(object);

    PyGILState_Release(state);
}

#endif
