// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef LINEAR_ACCELERATION_MESSAGE_H
#define LINEAR_ACCELERATION_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct
{
    PyObject_HEAD
    XIMU3_LinearAccelerationMessage message;
} LinearAccelerationMessage;

static void linear_acceleration_message_free(LinearAccelerationMessage* self)
{
    Py_TYPE(self)->tp_free(self);
}

static PyObject* linear_acceleration_message_get_timestamp(LinearAccelerationMessage* self)
{
    return Py_BuildValue("K", self->message.timestamp);
}

static PyObject* linear_acceleration_message_get_quaternion_w(LinearAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.quaternion_w);
}

static PyObject* linear_acceleration_message_get_quaternion_x(LinearAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.quaternion_x);
}

static PyObject* linear_acceleration_message_get_quaternion_y(LinearAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.quaternion_y);
}

static PyObject* linear_acceleration_message_get_quaternion_z(LinearAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.quaternion_z);
}

static PyObject* linear_acceleration_message_get_acceleration_x(LinearAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.acceleration_x);
}

static PyObject* linear_acceleration_message_get_acceleration_y(LinearAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.acceleration_y);
}

static PyObject* linear_acceleration_message_get_acceleration_z(LinearAccelerationMessage* self)
{
    return Py_BuildValue("f", self->message.acceleration_z);
}

static PyObject* linear_acceleration_message_to_string(LinearAccelerationMessage* self, PyObject* args)
{
    return Py_BuildValue("s", XIMU3_linear_acceleration_message_to_string(self->message));
}

static PyGetSetDef linear_acceleration_message_get_set[] = {
        { "timestamp",      (getter) linear_acceleration_message_get_timestamp,      NULL, "", NULL },
        { "quaternion_w",   (getter) linear_acceleration_message_get_quaternion_w,   NULL, "", NULL },
        { "quaternion_x",   (getter) linear_acceleration_message_get_quaternion_x,   NULL, "", NULL },
        { "quaternion_y",   (getter) linear_acceleration_message_get_quaternion_y,   NULL, "", NULL },
        { "quaternion_z",   (getter) linear_acceleration_message_get_quaternion_z,   NULL, "", NULL },
        { "acceleration_x", (getter) linear_acceleration_message_get_acceleration_x, NULL, "", NULL },
        { "acceleration_y", (getter) linear_acceleration_message_get_acceleration_y, NULL, "", NULL },
        { "acceleration_z", (getter) linear_acceleration_message_get_acceleration_z, NULL, "", NULL },
        { NULL } /* sentinel */
};

static PyMethodDef linear_acceleration_message_methods[] = {
        { "to_string", (PyCFunction) linear_acceleration_message_to_string, METH_NOARGS, "" },
        { NULL } /* sentinel */
};

static PyTypeObject linear_acceleration_message_object = {
        PyVarObject_HEAD_INIT(NULL, 0)
        .tp_name = "ximu3.LinearAccelerationMessage",
        .tp_basicsize = sizeof(LinearAccelerationMessage),
        .tp_dealloc = (destructor) linear_acceleration_message_free,
        .tp_getset = linear_acceleration_message_get_set,
        .tp_methods = linear_acceleration_message_methods,
};

static PyObject* linear_acceleration_message_from(const XIMU3_LinearAccelerationMessage* const message)
{
    LinearAccelerationMessage* const self = (LinearAccelerationMessage*) linear_acceleration_message_object.tp_alloc(&linear_acceleration_message_object, 0);
    self->message = *message;
    return (PyObject*) self;
}

static void linear_acceleration_message_callback(XIMU3_LinearAccelerationMessage data, void* context)
{
    const PyGILState_STATE state = PyGILState_Ensure();

    PyObject* const object = linear_acceleration_message_from(&data);
    PyObject* const tuple = Py_BuildValue("(O)", object);
    Py_DECREF(PyObject_CallObject((PyObject*) context, tuple));
    Py_DECREF(tuple);
    Py_DECREF(object);

    PyGILState_Release(state);
}

#endif
