// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef QUATERNION_MESSAGE_H
#define QUATERNION_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct
{
    PyObject_HEAD
    XIMU3_QuaternionMessage message;
} QuaternionMessage;

static void quaternion_message_free(QuaternionMessage* self)
{
    Py_TYPE(self)->tp_free(self);
}

static PyObject* quaternion_message_get_timestamp(QuaternionMessage* self)
{
    return Py_BuildValue("K", self->message.timestamp);
}

static PyObject* quaternion_message_get_w(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.w);
}

static PyObject* quaternion_message_get_x(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.x);
}

static PyObject* quaternion_message_get_y(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.y);
}

static PyObject* quaternion_message_get_z(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.z);
}

static PyObject* quaternion_message_to_string(QuaternionMessage* self, PyObject* args)
{
    return Py_BuildValue("s", XIMU3_quaternion_message_to_string(self->message));
}

static PyGetSetDef quaternion_message_get_set[] = {
        { "timestamp", (getter) quaternion_message_get_timestamp, NULL, "", NULL },
        { "w",         (getter) quaternion_message_get_w,         NULL, "", NULL },
        { "x",         (getter) quaternion_message_get_x,         NULL, "", NULL },
        { "y",         (getter) quaternion_message_get_y,         NULL, "", NULL },
        { "z",         (getter) quaternion_message_get_z,         NULL, "", NULL },
        { NULL }  /* sentinel */
};

static PyMethodDef quaternion_message_methods[] = {
        { "to_string", (PyCFunction) quaternion_message_to_string, METH_NOARGS, "" },
        { NULL } /* sentinel */
};

static PyTypeObject quaternion_message_object = {
        PyVarObject_HEAD_INIT(NULL, 0)
        .tp_name = "ximu3.QuaternionMessage",
        .tp_basicsize = sizeof(QuaternionMessage),
        .tp_dealloc = (destructor) quaternion_message_free,
        .tp_getset = quaternion_message_get_set,
        .tp_methods = quaternion_message_methods,
};

static PyObject* quaternion_message_from(const XIMU3_QuaternionMessage* const message)
{
    QuaternionMessage* const self = (QuaternionMessage*) quaternion_message_object.tp_alloc(&quaternion_message_object, 0);
    self->message = *message;
    return (PyObject*) self;
}

static void quaternion_message_callback(XIMU3_QuaternionMessage data, void* context)
{
    const PyGILState_STATE state = PyGILState_Ensure();

    PyObject* const object = quaternion_message_from(&data);
    PyObject* const tuple = Py_BuildValue("(O)", object);
    Py_DECREF(PyObject_CallObject((PyObject*) context, tuple));
    Py_DECREF(tuple);
    Py_DECREF(object);

    PyGILState_Release(state);
}

#endif
