// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef QUATERNION_MESSAGE_H
#define QUATERNION_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct
{
    PyObject_HEAD
    XIMU3_QuaternionMessage message;
} QuaternionMessage;

static void quaternion_message_free(QuaternionMessage* self)
{
    Py_TYPE(self)->tp_free(self);
}

static PyObject* quaternion_message_get_timestamp(QuaternionMessage* self)
{
    return Py_BuildValue("K", self->message.timestamp);
}

static PyObject* quaternion_message_get_w_element(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.w_element);
}

static PyObject* quaternion_message_get_x_element(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.x_element);
}

static PyObject* quaternion_message_get_y_element(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.y_element);
}

static PyObject* quaternion_message_get_z_element(QuaternionMessage* self)
{
    return Py_BuildValue("f", self->message.z_element);
}

static PyObject* quaternion_message_to_string(QuaternionMessage* self, PyObject* args)
{
    return Py_BuildValue("s", XIMU3_quaternion_message_to_string(self->message));
}

static PyGetSetDef quaternion_message_get_set[] = {
        { "timestamp", (getter) quaternion_message_get_timestamp, NULL, "", NULL },
        { "w_element", (getter) quaternion_message_get_w_element, NULL, "", NULL },
        { "x_element", (getter) quaternion_message_get_x_element, NULL, "", NULL },
        { "y_element", (getter) quaternion_message_get_y_element, NULL, "", NULL },
        { "z_element", (getter) quaternion_message_get_z_element, NULL, "", NULL },
        { NULL }  /* sentinel */
};

static PyMethodDef quaternion_message_methods[] = {
        { "to_string", (PyCFunction) quaternion_message_to_string, METH_NOARGS, "" },
        { NULL } /* sentinel */
};

static PyTypeObject quaternion_message_type = {
        PyVarObject_HEAD_INIT(NULL, 0)
        .tp_name = "ximu3.QuaternionMessage",
        .tp_basicsize = sizeof(QuaternionMessage),
        .tp_dealloc = (destructor) quaternion_message_free,
        .tp_getset = quaternion_message_get_set,
        .tp_methods = quaternion_message_methods,
};

static PyObject* quaternion_message_from(const XIMU3_QuaternionMessage* const message)
{
    QuaternionMessage* const self = (QuaternionMessage*) quaternion_message_type.tp_alloc(&quaternion_message_type, 0);
    self->message = *message;
    return (PyObject*) self;
}

typedef struct
{
    PyObject* callable;
    XIMU3_QuaternionMessage data;
} QuaternionPendingCallArg;

static int quaternion_message_pending_call_func(void* arg)
{
    PyObject* const object = quaternion_message_from(&((QuaternionPendingCallArg*) arg)->data);
    PyObject* const tuple = Py_BuildValue("(O)", object);
    Py_DECREF(PyObject_CallObject(((QuaternionPendingCallArg*) arg)->callable, tuple));
    Py_DECREF(tuple);
    Py_DECREF(object);
    free(arg);
    return 0;
}

static void quaternion_message_callback(XIMU3_QuaternionMessage data, void* context)
{
    QuaternionPendingCallArg* const arg = malloc(sizeof(QuaternionPendingCallArg));
    arg->callable = (PyObject*) context;
    arg->data = data;
    Py_AddPendingCall(&quaternion_message_pending_call_func, arg);
}

#endif
