// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef RSSI_MESSAGE_H
#define RSSI_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct
{
    PyObject_HEAD
    XIMU3_RssiMessage message;
} RssiMessage;

static void rssi_message_free(RssiMessage* self)
{
    Py_TYPE(self)->tp_free(self);
}

static PyObject* rssi_message_get_timestamp(RssiMessage* self)
{
    return Py_BuildValue("K", self->message.timestamp);
}

static PyObject* rssi_message_get_percentage(RssiMessage* self)
{
    return Py_BuildValue("f", self->message.percentage);
}

static PyObject* rssi_message_get_power(RssiMessage* self)
{
    return Py_BuildValue("f", self->message.power);
}

static PyObject* rssi_message_to_string(RssiMessage* self, PyObject* args)
{
    return Py_BuildValue("s", XIMU3_rssi_message_to_string(self->message));
}

static PyGetSetDef rssi_message_get_set[] = {
        { "timestamp",  (getter) rssi_message_get_timestamp,  NULL, "", NULL },
        { "percentage", (getter) rssi_message_get_percentage, NULL, "", NULL },
        { "power",      (getter) rssi_message_get_power,      NULL, "", NULL },
        { NULL }  /* sentinel */
};

static PyMethodDef rssi_message_methods[] = {
        { "to_string", (PyCFunction) rssi_message_to_string, METH_NOARGS, "" },
        { NULL } /* sentinel */
};

static PyTypeObject rssi_message_object = {
        PyVarObject_HEAD_INIT(NULL, 0)
        .tp_name = "ximu3.RssiMessage",
        .tp_basicsize = sizeof(RssiMessage),
        .tp_dealloc = (destructor) rssi_message_free,
        .tp_getset = rssi_message_get_set,
        .tp_methods = rssi_message_methods,
};

static PyObject* rssi_message_from(const XIMU3_RssiMessage* const message)
{
    RssiMessage* const self = (RssiMessage*) rssi_message_object.tp_alloc(&rssi_message_object, 0);
    self->message = *message;
    return (PyObject*) self;
}

static void rssi_message_callback(XIMU3_RssiMessage data, void* context)
{
    const PyGILState_STATE state = PyGILState_Ensure();

    PyObject* const object = rssi_message_from(&data);
    PyObject* const tuple = Py_BuildValue("(O)", object);
    Py_DECREF(PyObject_CallObject((PyObject*) context, tuple));
    Py_DECREF(tuple);
    Py_DECREF(object);

    PyGILState_Release(state);
}

#endif
