// This file was generated by Examples/C/generate_main.py

#include "Helpers.h"
#include <stdio.h>

void BluetoothConnection();

void Commands();

void DataLogger();

void Demux();

void FileConnection();

void FileConverter();

void GetPortNames();

void KeepOpen();

void NetworkAnnouncement();

void OpenAsync();

void Ping();

void PortScanner();

void SerialConnection();

void TcpConnection();

void UdpConnection();

void UsbConnection();

int main(int argc, const char* argv[])
{
    printf("Select example\n");
    printf("A. BluetoothConnection.c\n");
    printf("B. Commands.c\n");
    printf("C. DataLogger.c\n");
    printf("D. Demux.c\n");
    printf("E. FileConnection.c\n");
    printf("F. FileConverter.c\n");
    printf("G. GetPortNames.c\n");
    printf("H. KeepOpen.c\n");
    printf("I. NetworkAnnouncement.c\n");
    printf("J. OpenAsync.c\n");
    printf("K. Ping.c\n");
    printf("L. PortScanner.c\n");
    printf("M. SerialConnection.c\n");
    printf("N. TcpConnection.c\n");
    printf("O. UdpConnection.c\n");
    printf("P. UsbConnection.c\n");

    switch (GetKey())
    {
        case 'A':
            BluetoothConnection();
            break;
        case 'B':
            Commands();
            break;
        case 'C':
            DataLogger();
            break;
        case 'D':
            Demux();
            break;
        case 'E':
            FileConnection();
            break;
        case 'F':
            FileConverter();
            break;
        case 'G':
            GetPortNames();
            break;
        case 'H':
            KeepOpen();
            break;
        case 'I':
            NetworkAnnouncement();
            break;
        case 'J':
            OpenAsync();
            break;
        case 'K':
            Ping();
            break;
        case 'L':
            PortScanner();
            break;
        case 'M':
            SerialConnection();
            break;
        case 'N':
            TcpConnection();
            break;
        case 'O':
            UdpConnection();
            break;
        case 'P':
            UsbConnection();
            break;
    }
}
