// This file was generated by Examples/C/generate_main.py

#include "helpers.h"
#include <stdio.h>

void bluetooth_connection();

void commands();

void data_logger();

void file_connection();

void file_converter();

void get_port_names();

void keep_open();

void mux_connection();

void network_announcement();

void open_async();

void ping();

void port_scanner();

void serial_connection();

void tcp_connection();

void udp_connection();

void usb_connection();

int main(int argc, const char* argv[])
{
    printf("Select example\n");
    printf("A. bluetooth_connection.c\n");
    printf("B. commands.c\n");
    printf("C. data_logger.c\n");
    printf("D. file_connection.c\n");
    printf("E. file_converter.c\n");
    printf("F. get_port_names.c\n");
    printf("G. keep_open.c\n");
    printf("H. mux_connection.c\n");
    printf("I. network_announcement.c\n");
    printf("J. open_async.c\n");
    printf("K. ping.c\n");
    printf("L. port_scanner.c\n");
    printf("M. serial_connection.c\n");
    printf("N. tcp_connection.c\n");
    printf("O. udp_connection.c\n");
    printf("P. usb_connection.c\n");

    switch (get_key())
    {
        case 'A':
            bluetooth_connection();
            break;
        case 'B':
            commands();
            break;
        case 'C':
            data_logger();
            break;
        case 'D':
            file_connection();
            break;
        case 'E':
            file_converter();
            break;
        case 'F':
            get_port_names();
            break;
        case 'G':
            keep_open();
            break;
        case 'H':
            mux_connection();
            break;
        case 'I':
            network_announcement();
            break;
        case 'J':
            open_async();
            break;
        case 'K':
            ping();
            break;
        case 'L':
            port_scanner();
            break;
        case 'M':
            serial_connection();
            break;
        case 'N':
            tcp_connection();
            break;
        case 'O':
            udp_connection();
            break;
        case 'P':
            usb_connection();
            break;
    }
}
