#include "../../C/Ximu3.h"
#include "Connection.h"
#include "ConnectionInfo.h"
#include "DataLogger.h"
#include "DataMessages/DataMessages.h"
#include "DiscoveredNetworkDevice.h"
#include "DiscoveredSerialDevice.h"
#include "FileConverter.h"
#include "FileConverterProgress.h"
#include "NetworkDiscovery.h"
#include "PingResponse.h"
#include <Python.h>
#include "SerialDiscovery.h"
#include "Statistics.h"
#include <stdio.h>

static struct PyModuleDef config = {
        PyModuleDef_HEAD_INIT,
        "ximu3",
        "",
        -1,
};

bool add_object(PyObject* const module, PyTypeObject* const type_object, const char* const name)
{
    if (PyType_Ready(type_object) == 0)
    {
        Py_INCREF(type_object);
        if (PyModule_AddObject(module, name, (PyObject*) type_object) == 0)
        {
            return true;
        }
        Py_DECREF(type_object);
        return false;
    }
    return false;
}

PyMODINIT_FUNC PyInit_ximu3()
{
    PyObject* const module = PyModule_Create(&config);

    if (module != NULL &&
        add_object(module, &connection_object, "Connection") &&
        add_object(module, &usb_connection_info_object, "UsbConnectionInfo") &&
        add_object(module, &serial_connection_info_object, "SerialConnectionInfo") &&
        add_object(module, &tcp_connection_info_object, "TcpConnectionInfo") &&
        add_object(module, &udp_connection_info_object, "UdpConnectionInfo") &&
        add_object(module, &bluetooth_connection_info_object, "BluetoothConnectionInfo") &&
        add_object(module, &file_connection_info_object, "FileConnectionInfo") &&
        add_object(module, &data_logger_object, "DataLogger") &&
        add_object(module, &file_converter_object, "FileConverter") &&
        add_object(module, &file_converter_progress_object, "FileConverterProgress") &&
        // Start of code block #0 generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py
        add_object(module, &inertial_message_object, "InertialMessage") &&
        add_object(module, &magnetometer_message_object, "MagnetometerMessage") &&
        add_object(module, &quaternion_message_object, "QuaternionMessage") &&
        add_object(module, &rotation_matrix_message_object, "RotationMatrixMessage") &&
        add_object(module, &euler_angles_message_object, "EulerAnglesMessage") &&
        add_object(module, &linear_acceleration_message_object, "LinearAccelerationMessage") &&
        add_object(module, &earth_acceleration_message_object, "EarthAccelerationMessage") &&
        add_object(module, &high_g_accelerometer_message_object, "HighGAccelerometerMessage") &&
        add_object(module, &temperature_message_object, "TemperatureMessage") &&
        add_object(module, &battery_message_object, "BatteryMessage") &&
        add_object(module, &rssi_message_object, "RssiMessage") &&
        add_object(module, &serial_accessory_message_object, "SerialAccessoryMessage") &&
        add_object(module, &notification_message_object, "NotificationMessage") &&
        add_object(module, &error_message_object, "ErrorMessage") &&
        // End of code block #0 generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py
        add_object(module, &discovered_network_device_object, "DiscoveredNetworkDevice") &&
        add_object(module, &discovered_serial_device_object, "DiscoveredSerialDevice") &&
        add_object(module, &network_discovery_object, "NetworkDiscovery") &&
        add_object(module, &ping_response_object, "PingResponse") &&
        add_object(module, &serial_discovery_object, "SerialDiscovery") &&
        add_object(module, &statistics_object, "Statistics"))
    {
        return module;
    }

    Py_DECREF(module);

    return NULL;
}
