#include "../../C/Ximu3.h"
#include "Connection.h"
#include "ConnectionInfo.h"
#include "DataLogger.h"
#include "DataMessages/DataMessages.h"
#include "DiscoveredNetworkDevice.h"
#include "DiscoveredSerialDevice.h"
#include "FileConverter.h"
#include "FileConverterProgress.h"
#include "NetworkDiscovery.h"
#include "PingResponse.h"
#include <Python.h>
#include "SerialDiscovery.h"
#include "Statistics.h"
#include <stdio.h>

static struct PyModuleDef config = {
        PyModuleDef_HEAD_INIT,
        "ximu3",
        "",
        -1,
};

bool add_type(PyObject* const module, PyTypeObject* const type_object, const char* const name)
{
    if (PyType_Ready(type_object) == 0)
    {
        Py_INCREF(type_object);
        if (PyModule_AddObject(module, name, (PyObject*) type_object) == 0)
        {
            return true;
        }
        Py_DECREF(type_object);
        return false;
    }
    return false;
}

PyMODINIT_FUNC PyInit_ximu3()
{
    PyObject* const module = PyModule_Create(&config);

    if (module != NULL &&
        add_type(module, &connection_type, "Connection") &&
        add_type(module, &usb_connection_info_type, "UsbConnectionInfo") &&
        add_type(module, &serial_connection_info_type, "SerialConnectionInfo") &&
        add_type(module, &tcp_connection_info_type, "TcpConnectionInfo") &&
        add_type(module, &udp_connection_info_type, "UdpConnectionInfo") &&
        add_type(module, &bluetooth_connection_info_type, "BluetoothConnectionInfo") &&
        add_type(module, &file_connection_info_type, "FileConnectionInfo") &&
        add_type(module, &data_logger_type, "DataLogger") &&
        add_type(module, &file_converter_type, "FileConverter") &&
        add_type(module, &file_converter_progress_type, "FileConverterProgress") &&
        // Start of code block #0 generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py
        add_type(module, &inertial_message_type, "InertialMessage") &&
        add_type(module, &magnetometer_message_type, "MagnetometerMessage") &&
        add_type(module, &quaternion_message_type, "QuaternionMessage") &&
        add_type(module, &rotation_matrix_message_type, "RotationMatrixMessage") &&
        add_type(module, &euler_angles_message_type, "EulerAnglesMessage") &&
        add_type(module, &linear_acceleration_message_type, "LinearAccelerationMessage") &&
        add_type(module, &earth_acceleration_message_type, "EarthAccelerationMessage") &&
        add_type(module, &high_g_message_type, "HighGMessage") &&
        add_type(module, &temperature_message_type, "TemperatureMessage") &&
        add_type(module, &battery_message_type, "BatteryMessage") &&
        add_type(module, &rssi_message_type, "RssiMessage") &&
        add_type(module, &serial_message_type, "SerialMessage") &&
        add_type(module, &notification_message_type, "NotificationMessage") &&
        add_type(module, &error_message_type, "ErrorMessage") &&
        // End of code block #0 generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py
        add_type(module, &discovered_network_device_type, "DiscoveredNetworkDevice") &&
        add_type(module, &discovered_serial_device_type, "DiscoveredSerialDevice") &&
        add_type(module, &network_discovery_type, "NetworkDiscovery") &&
        add_type(module, &ping_response_type, "PingResponse") &&
        add_type(module, &serial_discovery_type, "SerialDiscovery") &&
        add_type(module, &statistics_type, "Statistics"))
    {
        return module;
    }

    Py_DECREF(module);

    return NULL;
}
