from collections.abc import Callable, Sequence

CHARGING_STATUS_NOT_CONNECTED: int
CHARGING_STATUS_CHARGING: int
CHARGING_STATUS_CHARGING_COMPLETE: int
CHARGING_STATUS_CHARGING_ON_HOLD: int
CONNECTION_STATUS_CONNECTED: int
CONNECTION_STATUS_RECONNECTING: int
DEFAULT_RETRIES: int
DEFAULT_TIMEOUT: int
FILE_CONVERTER_STATUS_COMPLETE: int
FILE_CONVERTER_STATUS_FAILED: int
FILE_CONVERTER_STATUS_IN_PROGRESS: int
PORT_TYPE_USB: int
PORT_TYPE_SERIAL: int
PORT_TYPE_BLUETOOTH: int
RECEIVE_ERROR_BUFFER_OVERRUN: int
RECEIVE_ERROR_INVALID_MESSAGE_IDENTIFIER: int
RECEIVE_ERROR_INVALID_JSON: int
RECEIVE_ERROR_JSON_IS_NOT_AN_OBJECT: int
RECEIVE_ERROR_JSON_OBJECT_IS_NOT_A_SINGLE_KEY_VALUE_PAIR: int
RECEIVE_ERROR_INVALID_MUX_MESSAGE_LENGTH: int
RECEIVE_ERROR_INVALID_ESCAPE_SEQUENCE: int
RECEIVE_ERROR_INVALID_BINARY_MESSAGE_LENGTH: int
RECEIVE_ERROR_UNABLE_TO_PARSE_ASCII_MESSAGE: int
RECEIVE_ERROR_UNKNOWN_ERROR: int
RESULT_OK: int
RESULT_ADDR_IN_USE: int
RESULT_ADDR_NOT_AVAILABLE: int
RESULT_ALREADY_EXISTS: int
RESULT_ARGUMENT_LIST_TOO_LONG: int
RESULT_BROKEN_PIPE: int
RESULT_CONNECTION_ABORTED: int
RESULT_CONNECTION_REFUSED: int
RESULT_CONNECTION_RESET: int
RESULT_DEADLOCK: int
RESULT_DIRECTORY_NOT_EMPTY: int
RESULT_EXECUTABLE_FILE_BUSY: int
RESULT_FILE_TOO_LARGE: int
RESULT_HOST_UNREACHABLE: int
RESULT_INTERRUPTED: int
RESULT_INVALID_DATA: int
RESULT_INVALID_INPUT: int
RESULT_IS_A_DIRECTORY: int
RESULT_NETWORK_DOWN: int
RESULT_NETWORK_UNREACHABLE: int
RESULT_NOT_A_DIRECTORY: int
RESULT_NOT_CONNECTED: int
RESULT_NOT_FOUND: int
RESULT_NOT_SEEKABLE: int
RESULT_OTHER: int
RESULT_OUT_OF_MEMORY: int
RESULT_PERMISSION_DENIED: int
RESULT_READ_ONLY_FILESYSTEM: int
RESULT_RESOURCE_BUSY: int
RESULT_STALE_NETWORK_FILE_HANDLE: int
RESULT_STORAGE_FULL: int
RESULT_TIMED_OUT: int
RESULT_TOO_MANY_LINKS: int
RESULT_UNEXPECTED_EOF: int
RESULT_UNSUPPORTED: int
RESULT_WOULD_BLOCK: int
RESULT_WRITE_ZERO: int
RESULT_UNKNOWN_ERROR: int

# charging_status_methods
def charging_status_from_float(status: float) -> int: ...
def charging_status_to_string(status: int) -> str: ...

# connection_status_methods
def connection_status_to_string(status: int) -> str: ...

# file_converter_status_methods
def file_converter_status_to_string(status: int) -> str: ...

# port_type_methods
def port_type_to_string(error: int) -> str: ...

# receive_error_methods
def receive_error_to_string(error: int) -> str: ...

# result_methods
def result_to_string(result: int) -> str: ...

# command_message_object
class CommandMessage:
    @property
    def json(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def error(self) -> str: ...
    @staticmethod
    def parse(json: str) -> CommandMessage: ...

# connection_object
class Connection:
    def __init__(
        self,
        config: UsbConnectionConfig | SerialConnectionConfig | TcpConnectionConfig | UdpConnectionConfig | BluetoothConnectionConfig | FileConnectionConfig | MuxConnectionConfig,
    ) -> None: ...
    def open(self) -> None: ...
    def open_async(self, callback: Callable[[int], None]) -> None: ...
    def close(self) -> None: ...
    def ping(self) -> PingResponse | None: ...
    def ping_async(self, callback: Callable[[PingResponse | None], None]) -> None: ...
    def send_command(self, command: str, retries: int = ..., timeout: int = ...) -> CommandMessage | None: ...
    def send_commands(self, commands: Sequence[str], retries: int = ..., timeout: int = ...) -> list[CommandMessage | None]: ...
    def send_command_async(self, commands: str, callback: Callable[[CommandMessage | None], None], retries: int = ..., timeout: int = ...) -> None: ...
    def send_commands_async(self, commands: Sequence[str], callback: Callable[[list[CommandMessage | None]], None], retries: int = ..., timeout: int = ...) -> None: ...
    def get_config(self) -> UsbConnectionConfig | SerialConnectionConfig | TcpConnectionConfig | UdpConnectionConfig | BluetoothConnectionConfig | FileConnectionConfig | MuxConnectionConfig: ...
    def get_statistics(self) -> Statistics: ...
    def add_receive_error_callback(self, callback: Callable[[int], None]) -> int: ...
    def add_statistics_callback(self, callback: Callable[[Statistics], None]) -> int: ...
    def add_inertial_callback(self, callback: Callable[[InertialMessage], None]) -> int: ...
    def add_magnetometer_callback(self, callback: Callable[[MagnetometerMessage], None]) -> int: ...
    def add_quaternion_callback(self, callback: Callable[[QuaternionMessage], None]) -> int: ...
    def add_rotation_matrix_callback(self, callback: Callable[[RotationMatrixMessage], None]) -> int: ...
    def add_euler_angles_callback(self, callback: Callable[[EulerAnglesMessage], None]) -> int: ...
    def add_linear_acceleration_callback(self, callback: Callable[[LinearAccelerationMessage], None]) -> int: ...
    def add_earth_acceleration_callback(self, callback: Callable[[EarthAccelerationMessage], None]) -> int: ...
    def add_ahrs_status_callback(self, callback: Callable[[AhrsStatusMessage], None]) -> int: ...
    def add_high_g_accelerometer_callback(self, callback: Callable[[HighGAccelerometerMessage], None]) -> int: ...
    def add_temperature_callback(self, callback: Callable[[TemperatureMessage], None]) -> int: ...
    def add_battery_callback(self, callback: Callable[[BatteryMessage], None]) -> int: ...
    def add_rssi_callback(self, callback: Callable[[RssiMessage], None]) -> int: ...
    def add_serial_accessory_callback(self, callback: Callable[[SerialAccessoryMessage], None]) -> int: ...
    def add_notification_callback(self, callback: Callable[[NotificationMessage], None]) -> int: ...
    def add_error_callback(self, callback: Callable[[ErrorMessage], None]) -> int: ...
    def add_end_of_file_callback(self, callback: Callable[[], None]) -> int: ...
    def remove_callback(self, callback_id: int) -> None: ...

# data_logger_object
class DataLogger:
    def __init__(self, destination: str, name: str, connections: Sequence[Connection]) -> None: ...
    @staticmethod
    def log(destination: str, name: str, connections: Sequence[Connection], seconds: int) -> None: ...

# device_object
class Device:
    @property
    def device_name(self) -> str: ...
    @property
    def serial_number(self) -> str: ...
    @property
    def connection_config(self) -> object: ...

# file_converter_object
class FileConverter:
    def __init__(self, destination: str, name: str, files: Sequence[str], callback: Callable[[FileConverterProgress], None]) -> None: ...
    @staticmethod
    def convert(destination: str, name: str, files: Sequence[str]) -> FileConverterProgress: ...

# file_converter_progress_object
class FileConverterProgress:
    @property
    def status(self) -> int: ...
    @property
    def percentage(self) -> float: ...
    @property
    def bytes_processed(self) -> int: ...
    @property
    def bytes_total(self) -> int: ...

# inertial_message_object
class InertialMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def gyroscope_x(self) -> float: ...
    @property
    def gyroscope_y(self) -> float: ...
    @property
    def gyroscope_z(self) -> float: ...
    @property
    def accelerometer_x(self) -> float: ...
    @property
    def accelerometer_y(self) -> float: ...
    @property
    def accelerometer_z(self) -> float: ...

# magnetometer_message_object
class MagnetometerMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...

# quaternion_message_object
class QuaternionMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def w(self) -> float: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def to_euler_angles_message(self) -> EulerAnglesMessage: ...

# rotation_matrix_message_object
class RotationMatrixMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def xx(self) -> float: ...
    @property
    def xy(self) -> float: ...
    @property
    def xz(self) -> float: ...
    @property
    def yx(self) -> float: ...
    @property
    def yy(self) -> float: ...
    @property
    def yz(self) -> float: ...
    @property
    def zx(self) -> float: ...
    @property
    def zy(self) -> float: ...
    @property
    def zz(self) -> float: ...
    def to_euler_angles_message(self) -> EulerAnglesMessage: ...

# euler_angles_message_object
class EulerAnglesMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def roll(self) -> float: ...
    @property
    def pitch(self) -> float: ...
    @property
    def yaw(self) -> float: ...
    def to_quaternion_message(self) -> QuaternionMessage: ...

# linear_acceleration_message_object
class LinearAccelerationMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def quaternion_w(self) -> float: ...
    @property
    def quaternion_x(self) -> float: ...
    @property
    def quaternion_y(self) -> float: ...
    @property
    def quaternion_z(self) -> float: ...
    @property
    def acceleration_x(self) -> float: ...
    @property
    def acceleration_y(self) -> float: ...
    @property
    def acceleration_z(self) -> float: ...
    def to_euler_angles_message(self) -> EulerAnglesMessage: ...

# earth_acceleration_message_object
class EarthAccelerationMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def quaternion_w(self) -> float: ...
    @property
    def quaternion_x(self) -> float: ...
    @property
    def quaternion_y(self) -> float: ...
    @property
    def quaternion_z(self) -> float: ...
    @property
    def acceleration_x(self) -> float: ...
    @property
    def acceleration_y(self) -> float: ...
    @property
    def acceleration_z(self) -> float: ...
    def to_euler_angles_message(self) -> EulerAnglesMessage: ...

# ahrs_status_message_object
class AhrsStatusMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def initialising(self) -> float: ...
    @property
    def angular_rate_recovery(self) -> float: ...
    @property
    def acceleration_recovery(self) -> float: ...
    @property
    def magnetic_recovery(self) -> float: ...

# high_g_accelerometer_message_object
class HighGAccelerometerMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...

# temperature_message_object
class TemperatureMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def temperature(self) -> float: ...

# battery_message_object
class BatteryMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def percentage(self) -> float: ...
    @property
    def voltage(self) -> float: ...
    @property
    def charging_status(self) -> float: ...

# rssi_message_object
class RssiMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def percentage(self) -> float: ...
    @property
    def power(self) -> float: ...

# serial_accessory_message_object
class SerialAccessoryMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def string(self) -> str: ...
    @property
    def bytes(self) -> bytearray: ...

# notification_message_object
class NotificationMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def string(self) -> str: ...
    @property
    def bytes(self) -> bytearray: ...

# error_message_object
class ErrorMessage:
    @property
    def timestamp(self) -> int: ...
    @property
    def string(self) -> str: ...
    @property
    def bytes(self) -> bytearray: ...

# keep_open_object
class KeepOpen:
    def __init__(self, connection: Connection, callback: Callable[[int], None]) -> None: ...

# network_announcement_object
class NetworkAnnouncement:
    def __init__(self) -> None: ...
    def add_callback(self, callback: Callable[[list[NetworkAnnouncementMessage]], None]) -> int: ...
    def remove_callback(self, callback_id: int) -> None: ...
    def get_messages(self) -> list[NetworkAnnouncementMessage]: ...
    def get_messages_after_short_delay(self) -> list[NetworkAnnouncementMessage]: ...

# network_announcement_message_object
class NetworkAnnouncementMessage:
    @property
    def device_name(self) -> str: ...
    @property
    def serial_number(self) -> str: ...
    @property
    def ip_address(self) -> str: ...
    @property
    def tcp_port(self) -> int: ...
    @property
    def udp_send(self) -> int: ...
    @property
    def udp_receive(self) -> int: ...
    @property
    def rssi(self) -> int: ...
    @property
    def battery(self) -> int: ...
    @property
    def charging_status(self) -> int: ...
    def to_tcp_connection_config(self) -> TcpConnectionConfig: ...
    def to_udp_connection_config(self) -> UdpConnectionConfig: ...

# ping_response_object
class PingResponse:
    @property
    def interface(self) -> str: ...
    @property
    def device_name(self) -> str: ...
    @property
    def serial_number(self) -> str: ...

# port_scanner_object
class PortScanner:
    def __init__(self, callback: Callable[[list[Device]], None]) -> None: ...
    def get_devices(self) -> list[Device]: ...
    @staticmethod
    def scan() -> list[Device]: ...
    @staticmethod
    def scan_filter(port_type: int) -> list[Device]: ...
    @staticmethod
    def get_port_names() -> list[str]: ...

# statistics_object
class Statistics:
    @property
    def timestamp(self) -> int: ...
    @property
    def data_total(self) -> int: ...
    @property
    def data_rate(self) -> int: ...
    @property
    def message_total(self) -> int: ...
    @property
    def message_rate(self) -> int: ...
    @property
    def error_total(self) -> int: ...
    @property
    def error_rate(self) -> int: ...

# usb_connection_config_object
class UsbConnectionConfig:
    def __init__(self, port_name: str) -> None: ...
    @property
    def port_name(self) -> str: ...
    @port_name.setter
    def port_name(self, value: str) -> None: ...

# serial_connection_config_object
class SerialConnectionConfig:
    def __init__(self, port_name: str, baud_rate: int, rts_cts_enabled: bool) -> None: ...
    @property
    def port_name(self) -> str: ...
    @port_name.setter
    def port_name(self, value: str) -> None: ...
    @property
    def baud_rate(self) -> int: ...
    @baud_rate.setter
    def baud_rate(self, value: int) -> None: ...
    @property
    def rts_cts_enabled(self) -> bool: ...
    @rts_cts_enabled.setter
    def rts_cts_enabled(self, value: bool) -> None: ...

# tcp_connection_config_object
class TcpConnectionConfig:
    def __init__(self, ip_address: str, port: int) -> None: ...
    @property
    def ip_address(self) -> str: ...
    @ip_address.setter
    def ip_address(self, value: str) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, value: int) -> None: ...

# udp_connection_config_object
class UdpConnectionConfig:
    def __init__(self, ip_address: str, send_port: int, receive_port: int) -> None: ...
    @property
    def ip_address(self) -> str: ...
    @ip_address.setter
    def ip_address(self, value: str) -> None: ...
    @property
    def send_port(self) -> int: ...
    @send_port.setter
    def send_port(self, value: int) -> None: ...
    @property
    def receive_port(self) -> int: ...
    @receive_port.setter
    def receive_port(self, value: int) -> None: ...

# bluetooth_connection_config_object
class BluetoothConnectionConfig:
    def __init__(self, port_name: str) -> None: ...
    @property
    def port_name(self) -> str: ...
    @port_name.setter
    def port_name(self, value: str) -> None: ...

# file_connection_config_object
class FileConnectionConfig:
    def __init__(self, file_path: str) -> None: ...
    @property
    def file_path(self) -> str: ...
    @file_path.setter
    def file_path(self, value: str) -> None: ...

# mux_connection_config_object
class MuxConnectionConfig:
    def __init__(self, channel: int, connection: Connection) -> None: ...
