// This file was generated by x-IMU3-GUI/Source/Windows/Graphs/generate_graph_windows.py

#include "../../Convert.h"
#include "BatteryVoltageGraphWindow.h"

Graph::Settings BatteryVoltageGraphWindow::settings = Graph::Settings(true);

BatteryVoltageGraphWindow::BatteryVoltageGraphWindow(const juce::ValueTree& windowLayout, const juce::Identifier& type_, DevicePanel& devicePanel_, GLRenderer& glRenderer)
        : GraphWindow(windowLayout, type_, devicePanel_, glRenderer, "Voltage (V)", {{{}, juce::Colours::yellow }}, settings)
{
    callbackIDs.push_back(devicePanel.getConnection().addBatteryCallback(batteryCallback = [&](auto message)
    {
        update(message.timestamp, { message.voltage });
    }));
}

BatteryVoltageGraphWindow::~BatteryVoltageGraphWindow()
{
    for (const auto callbackID : callbackIDs)
    {
        devicePanel.getConnection().removeCallback(callbackID);
    }
}
