// This file was generated by x-IMU3-GUI/Source/Windows/Graphs/generate_graph_windows.py

#include "ConnectionPanel/ConnectionPanel.h"
#include "ButtonGraphWindow.h"

ButtonGraphWindow::ButtonGraphWindow(const juce::ValueTree &windowLayout_, const juce::Identifier &type_, ConnectionPanel &connectionPanel_, OpenGLRenderer &openGLRenderer)
    : GraphWindow(windowLayout_, type_, connectionPanel_,
                  openGLRenderer,
                  "State",
                  {""},
                  {UIColours::graphChannel1},
                  true) {
    callbackIds.push_back(connectionPanel.getConnection()->addButtonCallback(buttonCallback = [&](auto message) {
        const auto state = message.state > 0.0f;
        update(message.timestamp, { state ? 0.0f : 1.0f });
        update(message.timestamp, { state ? 1.0f : 0.0f });
    }));
}

ButtonGraphWindow::~ButtonGraphWindow() {
    for (const auto callbackId: callbackIds) {
        connectionPanel.getConnection()->removeCallback(callbackId);
    }
}
