// This file was generated by x-IMU3-GUI/Source/Windows/Graphs/generate_graph_windows.py

#pragma once

#include "GraphWindow.h"
#include "OpenGL/Common/GLRenderer.h"
#include "Ximu3.hpp"

class EulerAnglesGraphWindow : public GraphWindow
{
public:
    EulerAnglesGraphWindow(const juce::ValueTree& windowLayout, const juce::Identifier& type_, DevicePanel& devicePanel_, GLRenderer& glRenderer);

    ~EulerAnglesGraphWindow() override;

private:
    static juce::ValueTree settingsTree_;

    std::vector<uint64_t> callbackIDs;
    std::function<void(ximu3::XIMU3_QuaternionMessage)> quaternionCallback;
    std::function<void(ximu3::XIMU3_RotationMatrixMessage)> rotationMatrixCallback;
    std::function<void(ximu3::XIMU3_EulerAnglesMessage)> eulerAnglesCallback;
    std::function<void(ximu3::XIMU3_LinearAccelerationMessage)> linearAccelerationCallback;
    std::function<void(ximu3::XIMU3_EarthAccelerationMessage)> earthAccelerationCallback;
};
