// This file was generated by x-IMU3-GUI/Source/Windows/Graphs/generate_graph_windows.py

#include "../../Convert.h"
#include "MagnetometerGraphWindow.h"

Graph::Settings MagnetometerGraphWindow::settings = Graph::Settings(false);

MagnetometerGraphWindow::MagnetometerGraphWindow(const juce::ValueTree& windowLayout, const juce::Identifier& type, DevicePanel& devicePanel_, GLRenderer& glRenderer)
        : GraphWindow(windowLayout, type, devicePanel_, glRenderer, "Intensity (a.u.)", {{ "X", UIColours::graphRed },
                                                                                         { "Y", UIColours::graphGreen },
                                                                                         { "Z", UIColours::graphBlue }}, settings)
{
    callbackIDs.push_back(devicePanel.getConnection().addMagnetometerCallback(magnetometerCallback = [&](auto message)
    {
        update(message.timestamp, { message.x_axis, message.y_axis, message.z_axis });
    }));
}

MagnetometerGraphWindow::~MagnetometerGraphWindow()
{
    for (const auto callbackID : callbackIDs)
    {
        devicePanel.getConnection().removeCallback(callbackID);
    }
}
