// This file was generated by x-IMU3-GUI/Source/Windows/Graphs/generate_graph_windows.py

#include "ConnectionPanel/ConnectionPanel.h"
#include "ReceivedMessageRateGraphWindow.h"

ReceivedMessageRateGraphWindow::ReceivedMessageRateGraphWindow(const juce::ValueTree &windowLayout_, const juce::Identifier &type_, ConnectionPanel &connectionPanel_, OpenGLRenderer &openGLRenderer)
    : GraphWindow(windowLayout_, type_, connectionPanel_,
                  openGLRenderer,
                  "Throughput (messages/s)",
                  {""},
                  {UIColours::graphChannel1},
                  true,
                  false) {
    callbackIds.push_back(connectionPanel.getConnection()->addStatisticsCallback(statisticsCallback = [&](auto message) {
        update(static_cast<uint64_t>(juce::Time::getMillisecondCounterHiRes() * 1000.0), {(float) message.message_rate});
    }));
}

ReceivedMessageRateGraphWindow::~ReceivedMessageRateGraphWindow() {
    for (const auto callbackId: callbackIds) {
        connectionPanel.getConnection()->removeCallback(callbackId);
    }
}
