// This file was generated by x-IMU3-GUI/Source/Windows/Graphs/generate_graph_windows.py

#include "ConnectionPanel/ConnectionPanel.h"
#include "SerialAccessoryCsvsGraphWindow.h"

SerialAccessoryCsvsGraphWindow::SerialAccessoryCsvsGraphWindow(const juce::ValueTree &windowLayout_, const juce::Identifier &type_, ConnectionPanel &connectionPanel_, OpenGLRenderer &openGLRenderer)
    : GraphWindow(windowLayout_, type_, connectionPanel_,
                  openGLRenderer,
                  "CSV",
                  {"1", "2", "3", "4", "5", "6", "7", "8"},
                  {UIColours::graphChannel1, UIColours::graphChannel2, UIColours::graphChannel3, UIColours::graphChannel4, UIColours::graphChannel5, UIColours::graphChannel6, UIColours::graphChannel7, UIColours::graphChannel8},
                  false,
                  true) {
    callbackIds.push_back(connectionPanel.getConnection()->addSerialAccessoryCallback(serialAccessoryCallback = [&](auto message) {
        for (size_t index = 0; index < message.number_of_bytes; index++) {
            if (message.char_array[index] < 0) {
                message.char_array[index] = ' ';
            }
        }

        std::vector<float> values;
        for (const auto &string: juce::StringArray::fromTokens(juce::String(message.char_array), ",", "")) {
            values.push_back(string.getFloatValue());
        }
        update(message.timestamp, values);
    }));
}

SerialAccessoryCsvsGraphWindow::~SerialAccessoryCsvsGraphWindow() {
    for (const auto callbackId: callbackIds) {
        connectionPanel.getConnection()->removeCallback(callbackId);
    }
}
