// This file was generated by x-IMU3-GUI/Source/Windows/Graphs/generate_graph_windows.py

#include "ConnectionPanel/ConnectionPanel.h"
#include "SyncGraphWindow.h"

SyncGraphWindow::SyncGraphWindow(const juce::ValueTree &windowLayout_, const juce::Identifier &type_, ConnectionPanel &connectionPanel_, OpenGLRenderer &openGLRenderer)
    : GraphWindow(windowLayout_, type_, connectionPanel_,
                  openGLRenderer,
                  "Edge",
                  {""},
                  {UIColours::graphChannel1},
                  true,
                  true) {
    callbackIds.push_back(connectionPanel.getConnection()->addSyncCallback(syncCallback = [&](auto message) {
        const auto edge = message.edge > 0.0f;
        update(message.timestamp, { edge ? 0.0f : 1.0f });
        update(message.timestamp, { edge ? 1.0f : 0.0f });
    }));
}

SyncGraphWindow::~SyncGraphWindow() {
    for (const auto callbackId: callbackIds) {
        connectionPanel.getConnection()->removeCallback(callbackId);
    }
}
