// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef BUTTON_MESSAGE_H
#define BUTTON_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_ButtonMessage wrapped;
} ButtonMessage;

static void button_message_free(ButtonMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *button_message_str(ButtonMessage *self) {
    const char *const string = XIMU3_button_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *button_message_get_timestamp(ButtonMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *button_message_get_state(ButtonMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.state);
}

static PyGetSetDef button_message_get_set[] = {
    {"timestamp", (getter) button_message_get_timestamp, NULL, "", NULL},
    {"state", (getter) button_message_get_state, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyTypeObject button_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.ButtonMessage",
    .tp_basicsize = sizeof(ButtonMessage),
    .tp_dealloc = (destructor) button_message_free,
    .tp_str = (reprfunc) button_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = button_message_get_set,
};

static PyObject *button_message_from(const XIMU3_ButtonMessage *const message) {
    ButtonMessage *const self = (ButtonMessage *) button_message_object.tp_alloc(&button_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void button_message_callback(XIMU3_ButtonMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = button_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
