// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef EARTH_ACCELERATION_MESSAGE_H
#define EARTH_ACCELERATION_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_EarthAccelerationMessage message;
} EarthAccelerationMessage;

static void earth_acceleration_message_free(EarthAccelerationMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *earth_acceleration_message_get_timestamp(EarthAccelerationMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->message.timestamp);
}

static PyObject *earth_acceleration_message_get_quaternion_w(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->message.quaternion_w);
}

static PyObject *earth_acceleration_message_get_quaternion_x(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->message.quaternion_x);
}

static PyObject *earth_acceleration_message_get_quaternion_y(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->message.quaternion_y);
}

static PyObject *earth_acceleration_message_get_quaternion_z(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->message.quaternion_z);
}

static PyObject *earth_acceleration_message_get_acceleration_x(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->message.acceleration_x);
}

static PyObject *earth_acceleration_message_get_acceleration_y(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->message.acceleration_y);
}

static PyObject *earth_acceleration_message_get_acceleration_z(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->message.acceleration_z);
}

static PyObject *earth_acceleration_message_to_string(EarthAccelerationMessage *self, PyObject *args) {
    const char *const string = XIMU3_earth_acceleration_message_to_string(self->message);

    return PyUnicode_FromString(string);
}

static PyObject *earth_acceleration_message_to_euler_angles_message(EarthAccelerationMessage *self, PyObject *args);

static PyGetSetDef earth_acceleration_message_get_set[] = {
    {"timestamp", (getter) earth_acceleration_message_get_timestamp, NULL, "", NULL},
    {"quaternion_w", (getter) earth_acceleration_message_get_quaternion_w, NULL, "", NULL},
    {"quaternion_x", (getter) earth_acceleration_message_get_quaternion_x, NULL, "", NULL},
    {"quaternion_y", (getter) earth_acceleration_message_get_quaternion_y, NULL, "", NULL},
    {"quaternion_z", (getter) earth_acceleration_message_get_quaternion_z, NULL, "", NULL},
    {"acceleration_x", (getter) earth_acceleration_message_get_acceleration_x, NULL, "", NULL},
    {"acceleration_y", (getter) earth_acceleration_message_get_acceleration_y, NULL, "", NULL},
    {"acceleration_z", (getter) earth_acceleration_message_get_acceleration_z, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef earth_acceleration_message_methods[] = {
    {"to_string", (PyCFunction) earth_acceleration_message_to_string, METH_NOARGS, ""},
    {"to_euler_angles_message", (PyCFunction) earth_acceleration_message_to_euler_angles_message, METH_NOARGS, ""},
    {NULL} /* sentinel */
};

static PyTypeObject earth_acceleration_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.EarthAccelerationMessage",
    .tp_basicsize = sizeof(EarthAccelerationMessage),
    .tp_dealloc = (destructor) earth_acceleration_message_free,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = earth_acceleration_message_get_set,
    .tp_methods = earth_acceleration_message_methods,
};

static PyObject *earth_acceleration_message_from(const XIMU3_EarthAccelerationMessage *const message) {
    EarthAccelerationMessage *const self = (EarthAccelerationMessage *) earth_acceleration_message_object.tp_alloc(&earth_acceleration_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->message = *message;
    return (PyObject *) self;
}

static void earth_acceleration_message_callback(XIMU3_EarthAccelerationMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = earth_acceleration_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
