// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef EULER_ANGLES_MESSAGE_H
#define EULER_ANGLES_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_EulerAnglesMessage wrapped;
} EulerAnglesMessage;

static void euler_angles_message_free(EulerAnglesMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *euler_angles_message_str(EulerAnglesMessage *self) {
    const char *const string = XIMU3_euler_angles_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *euler_angles_message_get_timestamp(EulerAnglesMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *euler_angles_message_get_roll(EulerAnglesMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.roll);
}

static PyObject *euler_angles_message_get_pitch(EulerAnglesMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.pitch);
}

static PyObject *euler_angles_message_get_yaw(EulerAnglesMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.yaw);
}

static PyObject *euler_angles_message_to_quaternion_message(EulerAnglesMessage *self, PyObject *args);

static PyGetSetDef euler_angles_message_get_set[] = {
    {"timestamp", (getter) euler_angles_message_get_timestamp, NULL, "", NULL},
    {"roll", (getter) euler_angles_message_get_roll, NULL, "", NULL},
    {"pitch", (getter) euler_angles_message_get_pitch, NULL, "", NULL},
    {"yaw", (getter) euler_angles_message_get_yaw, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef euler_angles_message_methods[] = {
    {"to_quaternion_message", (PyCFunction) euler_angles_message_to_quaternion_message, METH_NOARGS, ""},
    {NULL} /* sentinel */
};

static PyTypeObject euler_angles_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.EulerAnglesMessage",
    .tp_basicsize = sizeof(EulerAnglesMessage),
    .tp_dealloc = (destructor) euler_angles_message_free,
    .tp_str = (reprfunc) euler_angles_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = euler_angles_message_get_set,
    .tp_methods = euler_angles_message_methods,
};

static PyObject *euler_angles_message_from(const XIMU3_EulerAnglesMessage *const message) {
    EulerAnglesMessage *const self = (EulerAnglesMessage *) euler_angles_message_object.tp_alloc(&euler_angles_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void euler_angles_message_callback(XIMU3_EulerAnglesMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = euler_angles_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
