// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef INERTIAL_MESSAGE_H
#define INERTIAL_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_InertialMessage message;
} InertialMessage;

static void inertial_message_free(InertialMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *inertial_message_str(InertialMessage *self) {
    const char *const string = XIMU3_inertial_message_to_string(self->message);

    return PyUnicode_FromString(string);
}

static PyObject *inertial_message_get_timestamp(InertialMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->message.timestamp);
}

static PyObject *inertial_message_get_gyroscope_x(InertialMessage *self) {
    return PyFloat_FromDouble((double) self->message.gyroscope_x);
}

static PyObject *inertial_message_get_gyroscope_y(InertialMessage *self) {
    return PyFloat_FromDouble((double) self->message.gyroscope_y);
}

static PyObject *inertial_message_get_gyroscope_z(InertialMessage *self) {
    return PyFloat_FromDouble((double) self->message.gyroscope_z);
}

static PyObject *inertial_message_get_accelerometer_x(InertialMessage *self) {
    return PyFloat_FromDouble((double) self->message.accelerometer_x);
}

static PyObject *inertial_message_get_accelerometer_y(InertialMessage *self) {
    return PyFloat_FromDouble((double) self->message.accelerometer_y);
}

static PyObject *inertial_message_get_accelerometer_z(InertialMessage *self) {
    return PyFloat_FromDouble((double) self->message.accelerometer_z);
}

static PyGetSetDef inertial_message_get_set[] = {
    {"timestamp", (getter) inertial_message_get_timestamp, NULL, "", NULL},
    {"gyroscope_x", (getter) inertial_message_get_gyroscope_x, NULL, "", NULL},
    {"gyroscope_y", (getter) inertial_message_get_gyroscope_y, NULL, "", NULL},
    {"gyroscope_z", (getter) inertial_message_get_gyroscope_z, NULL, "", NULL},
    {"accelerometer_x", (getter) inertial_message_get_accelerometer_x, NULL, "", NULL},
    {"accelerometer_y", (getter) inertial_message_get_accelerometer_y, NULL, "", NULL},
    {"accelerometer_z", (getter) inertial_message_get_accelerometer_z, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef inertial_message_methods[] = {
    {NULL} /* sentinel */
};

static PyTypeObject inertial_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.InertialMessage",
    .tp_basicsize = sizeof(InertialMessage),
    .tp_dealloc = (destructor) inertial_message_free,
    .tp_str = (reprfunc) inertial_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = inertial_message_get_set,
    .tp_methods = inertial_message_methods,
};

static PyObject *inertial_message_from(const XIMU3_InertialMessage *const message) {
    InertialMessage *const self = (InertialMessage *) inertial_message_object.tp_alloc(&inertial_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->message = *message;
    return (PyObject *) self;
}

static void inertial_message_callback(XIMU3_InertialMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = inertial_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
