// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef MAGNETOMETER_MESSAGE_H
#define MAGNETOMETER_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_MagnetometerMessage wrapped;
} MagnetometerMessage;

static void magnetometer_message_free(MagnetometerMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *magnetometer_message_str(MagnetometerMessage *self) {
    const char *const string = XIMU3_magnetometer_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *magnetometer_message_get_timestamp(MagnetometerMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *magnetometer_message_get_x(MagnetometerMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.x);
}

static PyObject *magnetometer_message_get_y(MagnetometerMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.y);
}

static PyObject *magnetometer_message_get_z(MagnetometerMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.z);
}

static PyGetSetDef magnetometer_message_get_set[] = {
    {"timestamp", (getter) magnetometer_message_get_timestamp, NULL, "", NULL},
    {"x", (getter) magnetometer_message_get_x, NULL, "", NULL},
    {"y", (getter) magnetometer_message_get_y, NULL, "", NULL},
    {"z", (getter) magnetometer_message_get_z, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef magnetometer_message_methods[] = {
    {NULL} /* sentinel */
};

static PyTypeObject magnetometer_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.MagnetometerMessage",
    .tp_basicsize = sizeof(MagnetometerMessage),
    .tp_dealloc = (destructor) magnetometer_message_free,
    .tp_str = (reprfunc) magnetometer_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = magnetometer_message_get_set,
    .tp_methods = magnetometer_message_methods,
};

static PyObject *magnetometer_message_from(const XIMU3_MagnetometerMessage *const message) {
    MagnetometerMessage *const self = (MagnetometerMessage *) magnetometer_message_object.tp_alloc(&magnetometer_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void magnetometer_message_callback(XIMU3_MagnetometerMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = magnetometer_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
