// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef QUATERNION_MESSAGE_H
#define QUATERNION_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_QuaternionMessage wrapped;
} QuaternionMessage;

static void quaternion_message_free(QuaternionMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *quaternion_message_str(QuaternionMessage *self) {
    const char *const string = XIMU3_quaternion_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *quaternion_message_get_timestamp(QuaternionMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *quaternion_message_get_w(QuaternionMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.w);
}

static PyObject *quaternion_message_get_x(QuaternionMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.x);
}

static PyObject *quaternion_message_get_y(QuaternionMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.y);
}

static PyObject *quaternion_message_get_z(QuaternionMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.z);
}

static PyObject *quaternion_message_to_euler_angles_message(QuaternionMessage *self, PyObject *args);

static PyGetSetDef quaternion_message_get_set[] = {
    {"timestamp", (getter) quaternion_message_get_timestamp, NULL, "", NULL},
    {"w", (getter) quaternion_message_get_w, NULL, "", NULL},
    {"x", (getter) quaternion_message_get_x, NULL, "", NULL},
    {"y", (getter) quaternion_message_get_y, NULL, "", NULL},
    {"z", (getter) quaternion_message_get_z, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef quaternion_message_methods[] = {
    {"to_euler_angles_message", (PyCFunction) quaternion_message_to_euler_angles_message, METH_NOARGS, ""},
    {NULL} /* sentinel */
};

static PyTypeObject quaternion_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.QuaternionMessage",
    .tp_basicsize = sizeof(QuaternionMessage),
    .tp_dealloc = (destructor) quaternion_message_free,
    .tp_str = (reprfunc) quaternion_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = quaternion_message_get_set,
    .tp_methods = quaternion_message_methods,
};

static PyObject *quaternion_message_from(const XIMU3_QuaternionMessage *const message) {
    QuaternionMessage *const self = (QuaternionMessage *) quaternion_message_object.tp_alloc(&quaternion_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void quaternion_message_callback(XIMU3_QuaternionMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = quaternion_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
