// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef ROTATION_MATRIX_MESSAGE_H
#define ROTATION_MATRIX_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_RotationMatrixMessage message;
} RotationMatrixMessage;

static void rotation_matrix_message_free(RotationMatrixMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *rotation_matrix_message_get_timestamp(RotationMatrixMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->message.timestamp);
}

static PyObject *rotation_matrix_message_get_xx(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.xx);
}

static PyObject *rotation_matrix_message_get_xy(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.xy);
}

static PyObject *rotation_matrix_message_get_xz(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.xz);
}

static PyObject *rotation_matrix_message_get_yx(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.yx);
}

static PyObject *rotation_matrix_message_get_yy(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.yy);
}

static PyObject *rotation_matrix_message_get_yz(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.yz);
}

static PyObject *rotation_matrix_message_get_zx(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.zx);
}

static PyObject *rotation_matrix_message_get_zy(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.zy);
}

static PyObject *rotation_matrix_message_get_zz(RotationMatrixMessage *self) {
    return PyFloat_FromDouble((double) self->message.zz);
}

static PyObject *rotation_matrix_message_to_string(RotationMatrixMessage *self, PyObject *args) {
    const char *const string = XIMU3_rotation_matrix_message_to_string(self->message);

    return PyUnicode_FromString(string);
}

static PyObject *rotation_matrix_message_to_euler_angles_message(RotationMatrixMessage *self, PyObject *args);

static PyGetSetDef rotation_matrix_message_get_set[] = {
    {"timestamp", (getter) rotation_matrix_message_get_timestamp, NULL, "", NULL},
    {"xx", (getter) rotation_matrix_message_get_xx, NULL, "", NULL},
    {"xy", (getter) rotation_matrix_message_get_xy, NULL, "", NULL},
    {"xz", (getter) rotation_matrix_message_get_xz, NULL, "", NULL},
    {"yx", (getter) rotation_matrix_message_get_yx, NULL, "", NULL},
    {"yy", (getter) rotation_matrix_message_get_yy, NULL, "", NULL},
    {"yz", (getter) rotation_matrix_message_get_yz, NULL, "", NULL},
    {"zx", (getter) rotation_matrix_message_get_zx, NULL, "", NULL},
    {"zy", (getter) rotation_matrix_message_get_zy, NULL, "", NULL},
    {"zz", (getter) rotation_matrix_message_get_zz, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef rotation_matrix_message_methods[] = {
    {"to_string", (PyCFunction) rotation_matrix_message_to_string, METH_NOARGS, ""},
    {"to_euler_angles_message", (PyCFunction) rotation_matrix_message_to_euler_angles_message, METH_NOARGS, ""},
    {NULL} /* sentinel */
};

static PyTypeObject rotation_matrix_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.RotationMatrixMessage",
    .tp_basicsize = sizeof(RotationMatrixMessage),
    .tp_dealloc = (destructor) rotation_matrix_message_free,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = rotation_matrix_message_get_set,
    .tp_methods = rotation_matrix_message_methods,
};

static PyObject *rotation_matrix_message_from(const XIMU3_RotationMatrixMessage *const message) {
    RotationMatrixMessage *const self = (RotationMatrixMessage *) rotation_matrix_message_object.tp_alloc(&rotation_matrix_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->message = *message;
    return (PyObject *) self;
}

static void rotation_matrix_message_callback(XIMU3_RotationMatrixMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = rotation_matrix_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
