// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef SERIAL_ACCESSORY_MESSAGE_H
#define SERIAL_ACCESSORY_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_SerialAccessoryMessage message;
} SerialAccessoryMessage;

static void serial_accessory_message_free(SerialAccessoryMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *serial_accessory_message_get_timestamp(SerialAccessoryMessage *self, PyObject *args) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->message.timestamp);
}

static PyObject *serial_accessory_message_get_string(SerialAccessoryMessage *self, PyObject *args) {
    return PyUnicode_FromString(self->message.char_array);
}

static PyObject *serial_accessory_message_get_bytes(SerialAccessoryMessage *self, PyObject *args) {
    return PyByteArray_FromStringAndSize(self->message.char_array, (Py_ssize_t) self->message.number_of_bytes);
}

static PyObject *serial_accessory_message_to_string(SerialAccessoryMessage *self, PyObject *args) {
    const char *const string = XIMU3_serial_accessory_message_to_string(self->message);

    return PyUnicode_FromString(string);
}

static PyGetSetDef serial_accessory_message_get_set[] = {
    {"timestamp", (getter) serial_accessory_message_get_timestamp, NULL, "", NULL},
    {"string", (getter) serial_accessory_message_get_string, NULL, "", NULL},
    {"bytes", (getter) serial_accessory_message_get_bytes, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef serial_accessory_message_methods[] = {
    {"to_string", (PyCFunction) serial_accessory_message_to_string, METH_NOARGS, ""},
    {NULL} /* sentinel */
};

static PyTypeObject serial_accessory_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.SerialAccessoryMessage",
    .tp_basicsize = sizeof(SerialAccessoryMessage),
    .tp_dealloc = (destructor) serial_accessory_message_free,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = serial_accessory_message_get_set,
    .tp_methods = serial_accessory_message_methods,
};

static PyObject *serial_accessory_message_from(const XIMU3_SerialAccessoryMessage *const message) {
    SerialAccessoryMessage *const self = (SerialAccessoryMessage *) serial_accessory_message_object.tp_alloc(&serial_accessory_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->message = *message;
    return (PyObject *) self;
}

static void serial_accessory_message_callback(XIMU3_SerialAccessoryMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = serial_accessory_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
