// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef SYNC_MESSAGE_H
#define SYNC_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_SyncMessage wrapped;
} SyncMessage;

static void sync_message_free(SyncMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *sync_message_str(SyncMessage *self) {
    const char *const string = XIMU3_sync_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *sync_message_get_timestamp(SyncMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *sync_message_get_edge(SyncMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.edge);
}

static PyGetSetDef sync_message_get_set[] = {
    {"timestamp", (getter) sync_message_get_timestamp, NULL, "", NULL},
    {"edge", (getter) sync_message_get_edge, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyTypeObject sync_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.SyncMessage",
    .tp_basicsize = sizeof(SyncMessage),
    .tp_dealloc = (destructor) sync_message_free,
    .tp_str = (reprfunc) sync_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = sync_message_get_set,
};

static PyObject *sync_message_from(const XIMU3_SyncMessage *const message) {
    SyncMessage *const self = (SyncMessage *) sync_message_object.tp_alloc(&sync_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void sync_message_callback(XIMU3_SyncMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = sync_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
