// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef TEMPERATURE_MESSAGE_H
#define TEMPERATURE_MESSAGE_H

#include "../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_TemperatureMessage message;
} TemperatureMessage;

static void temperature_message_free(TemperatureMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *temperature_message_get_timestamp(TemperatureMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->message.timestamp);
}

static PyObject *temperature_message_get_temperature(TemperatureMessage *self) {
    return PyFloat_FromDouble((double) self->message.temperature);
}

static PyObject *temperature_message_to_string(TemperatureMessage *self, PyObject *args) {
    const char *const string = XIMU3_temperature_message_to_string(self->message);

    return PyUnicode_FromString(string);
}

static PyGetSetDef temperature_message_get_set[] = {
    {"timestamp", (getter) temperature_message_get_timestamp, NULL, "", NULL},
    {"temperature", (getter) temperature_message_get_temperature, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyMethodDef temperature_message_methods[] = {
    {"to_string", (PyCFunction) temperature_message_to_string, METH_NOARGS, ""},
    {NULL} /* sentinel */
};

static PyTypeObject temperature_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.TemperatureMessage",
    .tp_basicsize = sizeof(TemperatureMessage),
    .tp_dealloc = (destructor) temperature_message_free,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = temperature_message_get_set,
    .tp_methods = temperature_message_methods,
};

static PyObject *temperature_message_from(const XIMU3_TemperatureMessage *const message) {
    TemperatureMessage *const self = (TemperatureMessage *) temperature_message_object.tp_alloc(&temperature_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->message = *message;
    return (PyObject *) self;
}

static void temperature_message_callback(XIMU3_TemperatureMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = temperature_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
