// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

use std::fmt;
use std::mem::size_of;
use crate::data_messages::*;
use crate::decode_error::*;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct AhrsStatusMessage {
    pub timestamp: u64,
    pub initialising: f32,
    pub angular_rate_recovery: f32,
    pub acceleration_recovery: f32,
    pub magnetic_recovery: f32,
}

impl DataMessage for AhrsStatusMessage {
    fn get_ascii_id() -> u8 {
        'U' as u8
    }

    fn parse_ascii(message: &str) -> Result<Self, DecodeError> {
        match scan_fmt!( message, "{},{d},{f},{f},{f},{f}\r\n",  char, u64, f32, f32, f32, f32) {
            Ok((_, timestamp, initialising, angular_rate_recovery, acceleration_recovery, magnetic_recovery)) => Ok(AhrsStatusMessage { timestamp, initialising, angular_rate_recovery, acceleration_recovery, magnetic_recovery }),
            Err(_) => Err(DecodeError::UnableToParseAsciiMessage),
        }
    }

    fn parse_binary(message: &[u8]) -> Result<Self, DecodeError> {
        #[repr(C, packed)]
        struct BinaryMessage {
            id: u8,
            timestamp: u64,
            initialising: f32,
            angular_rate_recovery: f32,
            acceleration_recovery: f32,
            magnetic_recovery: f32,
            termination: u8,
        }

        if message.len() != size_of::<BinaryMessage>() {
            return Err(DecodeError::InvalidBinaryMessageLength);
        }

        let binary_message = unsafe {
            let ref binary_message = *(message.as_ptr() as *const BinaryMessage);
            binary_message
        };

        Ok(AhrsStatusMessage { timestamp: binary_message.timestamp, initialising: binary_message.initialising, angular_rate_recovery: binary_message.angular_rate_recovery, acceleration_recovery: binary_message.acceleration_recovery, magnetic_recovery: binary_message.magnetic_recovery })
    }

    fn get_csv_file_name(&self) -> &'static str {
        "AhrsStatus.csv"
    }

    fn get_csv_headings(&self) -> &'static str {
        "Timestamp (us),Initialising,Angular Rate Recovery,Acceleration Recovery,Magnetic Recovery\n"
    }

    fn to_csv_row(&self) -> String {
        format!("{},{:.6},{:.6},{:.6},{:.6}\n", self.timestamp, self.initialising, self.angular_rate_recovery, self.acceleration_recovery, self.magnetic_recovery)
    }
}

impl fmt::Display for AhrsStatusMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "{:>8} us {:>8.3} {:>8.3} {:>8.3} {:>8.3}", self.timestamp, self.initialising, self.angular_rate_recovery, self.acceleration_recovery, self.magnetic_recovery)
    }
}
