// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

use std::fmt;
use std::mem::size_of;
use crate::data_messages::*;
use crate::decode_error::*;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct EarthAccelerationMessage {
    pub timestamp: u64,
    pub quaternion_w: f32,
    pub quaternion_x: f32,
    pub quaternion_y: f32,
    pub quaternion_z: f32,
    pub acceleration_x: f32,
    pub acceleration_y: f32,
    pub acceleration_z: f32,
}

impl DataMessage for EarthAccelerationMessage {
    fn get_ascii_id() -> u8 {
        'E' as u8
    }

    fn parse_ascii(message: &str) -> Result<Self, DecodeError> {
        match scan_fmt!( message, "{},{d},{f},{f},{f},{f},{f},{f},{f}\r\n",  char, u64, f32, f32, f32, f32, f32, f32, f32) {
            Ok((_, timestamp, quaternion_w, quaternion_x, quaternion_y, quaternion_z, acceleration_x, acceleration_y, acceleration_z)) => Ok(EarthAccelerationMessage { timestamp, quaternion_w, quaternion_x, quaternion_y, quaternion_z, acceleration_x, acceleration_y, acceleration_z }),
            Err(_) => Err(DecodeError::UnableToParseAsciiMessage),
        }
    }

    fn parse_binary(message: &[u8]) -> Result<Self, DecodeError> {
        #[repr(C, packed)]
        struct BinaryMessage {
            id: u8,
            timestamp: u64,
            quaternion_w: f32,
            quaternion_x: f32,
            quaternion_y: f32,
            quaternion_z: f32,
            acceleration_x: f32,
            acceleration_y: f32,
            acceleration_z: f32,
            termination: u8,
        }

        if message.len() != size_of::<BinaryMessage>() {
            return Err(DecodeError::InvalidBinaryMessageLength);
        }

        let binary_message = unsafe {
            let ref binary_message = *(message.as_ptr() as *const BinaryMessage);
            binary_message
        };

        Ok(EarthAccelerationMessage { timestamp: binary_message.timestamp, quaternion_w: binary_message.quaternion_w, quaternion_x: binary_message.quaternion_x, quaternion_y: binary_message.quaternion_y, quaternion_z: binary_message.quaternion_z, acceleration_x: binary_message.acceleration_x, acceleration_y: binary_message.acceleration_y, acceleration_z: binary_message.acceleration_z })
    }

    fn get_csv_file_name(&self) -> &'static str {
        "EarthAcceleration.csv"
    }

    fn get_csv_headings(&self) -> &'static str {
        "Timestamp (us),Quaternion W,Quaternion X,Quaternion Y,Quaternion Z,Acceleration X (g),Acceleration Y (g),Acceleration Z (g)\n"
    }

    fn to_csv_row(&self) -> String {
        format!("{},{:.6},{:.6},{:.6},{:.6},{:.6},{:.6},{:.6}\n", self.timestamp, self.quaternion_w, self.quaternion_x, self.quaternion_y, self.quaternion_z, self.acceleration_x, self.acceleration_y, self.acceleration_z)
    }
}

impl fmt::Display for EarthAccelerationMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "{:>8} us {:>8.3} {:>8.3} {:>8.3} {:>8.3} {:>8.3} g {:>8.3} g {:>8.3} g", self.timestamp, self.quaternion_w, self.quaternion_x, self.quaternion_y, self.quaternion_z, self.acceleration_x, self.acceleration_y, self.acceleration_z)
    }
}
