// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

use std::fmt;
use std::mem::size_of;
use crate::data_messages::*;
use crate::decode_error::*;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct MagnetometerMessage {
    pub timestamp: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl DataMessage for MagnetometerMessage {
    fn get_ascii_id() -> u8 {
        'M' as u8
    }

    fn parse_ascii(message: &str) -> Result<Self, DecodeError> {
        match scan_fmt!( message, "{},{d},{f},{f},{f}\r\n",  char, u64, f32, f32, f32) {
            Ok((_, timestamp, x, y, z)) => Ok(MagnetometerMessage { timestamp, x, y, z }),
            Err(_) => Err(DecodeError::UnableToParseAsciiMessage),
        }
    }

    fn parse_binary(message: &[u8]) -> Result<Self, DecodeError> {
        #[repr(C, packed)]
        struct BinaryMessage {
            id: u8,
            timestamp: u64,
            x: f32,
            y: f32,
            z: f32,
            termination: u8,
        }

        if message.len() != size_of::<BinaryMessage>() {
            return Err(DecodeError::InvalidBinaryMessageLength);
        }

        let binary_message = unsafe {
            let ref binary_message = *(message.as_ptr() as *const BinaryMessage);
            binary_message
        };

        Ok(MagnetometerMessage { timestamp: binary_message.timestamp, x: binary_message.x, y: binary_message.y, z: binary_message.z })
    }

    fn get_csv_file_name(&self) -> &'static str {
        "Magnetometer.csv"
    }

    fn get_csv_headings(&self) -> &'static str {
        "Timestamp (us),X (a.u.),Y (a.u.),Z (a.u.)\n"
    }

    fn to_csv_row(&self) -> String {
        format!("{},{:.6},{:.6},{:.6}\n", self.timestamp, self.x, self.y, self.z)
    }
}

impl fmt::Display for MagnetometerMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "{:>8} us {:>8.3} a.u. {:>8.3} a.u. {:>8.3} a.u.", self.timestamp, self.x, self.y, self.z)
    }
}
