// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

use std::fmt;
use std::mem::size_of;
use crate::data_messages::*;
use crate::decode_error::*;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct QuaternionMessage {
    pub timestamp: u64,
    pub w_element: f32,
    pub x_element: f32,
    pub y_element: f32,
    pub z_element: f32,
}

impl DataMessage for QuaternionMessage {
    fn get_ascii_id() -> u8 {
        'Q' as u8
    }

    fn parse_ascii(message: &str) -> Result<Self, DecodeError> {
        match scan_fmt!( message, "{},{d},{f},{f},{f},{f}\r\n",  char, u64, f32, f32, f32, f32) {
            Ok((_, timestamp, w_element, x_element, y_element, z_element)) => Ok(QuaternionMessage { timestamp, w_element, x_element, y_element, z_element }),
            Err(_) => Err(DecodeError::UnableToParseAsciiMessage),
        }
    }

    fn parse_binary(message: &[u8]) -> Result<Self, DecodeError> {
        #[repr(C, packed)]
        struct BinaryMessage {
            id: u8,
            timestamp: u64,
            w_element: f32,
            x_element: f32,
            y_element: f32,
            z_element: f32,
            termination: u8,
        }

        if message.len() != size_of::<BinaryMessage>() {
            return Err(DecodeError::InvalidBinaryMessageLength);
        }

        let binary_message = unsafe {
            let ref binary_message = *(message.as_ptr() as *const BinaryMessage);
            binary_message
        };

        Ok(QuaternionMessage { timestamp: binary_message.timestamp, w_element: binary_message.w_element, x_element: binary_message.x_element, y_element: binary_message.y_element, z_element: binary_message.z_element })
    }

    fn get_csv_file_name(&self) -> &'static str {
        "Quaternion.csv"
    }

    fn get_csv_headings(&self) -> &'static str {
        "Timestamp (us),W Element,X Element,Y Element,Z Element\n"
    }

    fn to_csv_row(&self) -> String {
        format!("{},{:.6},{:.6},{:.6},{:.6}\n", self.timestamp, self.w_element, self.x_element, self.y_element, self.z_element)
    }
}

impl fmt::Display for QuaternionMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "{:>8} us {:>8.3} {:>8.3} {:>8.3} {:>8.3}", self.timestamp, self.w_element, self.x_element, self.y_element, self.z_element)
    }
}
