// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

use std::fmt;
use std::mem::size_of;
use crate::data_messages::*;
use crate::decode_error::*;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct QuaternionMessage {
    pub timestamp: u64,
    pub w: f32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl DataMessage for QuaternionMessage {
    fn get_ascii_id() -> u8 {
        'Q' as u8
    }

    fn parse_ascii(message: &str) -> Result<Self, DecodeError> {
        match scan_fmt!( message, "{},{d},{f},{f},{f},{f}\r\n",  char, u64, f32, f32, f32, f32) {
            Ok((_, timestamp, w, x, y, z)) => Ok(QuaternionMessage { timestamp, w, x, y, z }),
            Err(_) => Err(DecodeError::UnableToParseAsciiMessage),
        }
    }

    fn parse_binary(message: &[u8]) -> Result<Self, DecodeError> {
        #[repr(C, packed)]
        struct BinaryMessage {
            id: u8,
            timestamp: u64,
            w: f32,
            x: f32,
            y: f32,
            z: f32,
            termination: u8,
        }

        if message.len() != size_of::<BinaryMessage>() {
            return Err(DecodeError::InvalidBinaryMessageLength);
        }

        let binary_message = unsafe {
            let ref binary_message = *(message.as_ptr() as *const BinaryMessage);
            binary_message
        };

        Ok(QuaternionMessage { timestamp: binary_message.timestamp, w: binary_message.w, x: binary_message.x, y: binary_message.y, z: binary_message.z })
    }

    fn get_csv_file_name(&self) -> &'static str {
        "Quaternion.csv"
    }

    fn get_csv_headings(&self) -> &'static str {
        "Timestamp (us),W,X,Y,Z\n"
    }

    fn to_csv_row(&self) -> String {
        format!("{},{:.6},{:.6},{:.6},{:.6}\n", self.timestamp, self.w, self.x, self.y, self.z)
    }
}

impl fmt::Display for QuaternionMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "{:>8} us {:>8.3} {:>8.3} {:>8.3} {:>8.3}", self.timestamp, self.w, self.x, self.y, self.z)
    }
}
