// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

use crate::data_messages::*;
use crate::receive_error::*;
use std::fmt;
use std::mem::size_of;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct RssiMessage {
    pub timestamp: u64,
    pub percentage: f32,
    pub power: f32,
}

impl DataMessage for RssiMessage {
    fn get_ascii_id() -> u8 {
        b'W'
    }

    fn parse_ascii(message: &str) -> Result<Self, ReceiveError> {
        match scan_fmt!(message, "{},{d},{f},{f}\n", char, u64, f32, f32) {
            Ok((_, timestamp, percentage, power)) => Ok(Self {
                timestamp,
                percentage,
                power,
            }),
            Err(_) => Err(ReceiveError::UnableToParseAsciiMessage),
        }
    }

    fn parse_binary(message: &[u8]) -> Result<Self, ReceiveError> {
        #[repr(C, packed)]
        struct BinaryMessage {
            _id: u8,
            timestamp: u64,
            percentage: f32,
            power: f32,
            _termination: u8,
        }

        if message.len() != size_of::<BinaryMessage>() {
            return Err(ReceiveError::InvalidBinaryMessageLength);
        }

        let binary_message = unsafe {
            let ref binary_message = *(message.as_ptr() as *const BinaryMessage);
            binary_message
        };

        Ok(Self {
            timestamp: binary_message.timestamp,
            percentage: binary_message.percentage,
            power: binary_message.power,
        })
    }

    fn get_csv_file_name(&self) -> &'static str {
        "Rssi.csv"
    }

    fn get_csv_headings(&self) -> &'static str {
        "Timestamp (us),Percentage (%),Power (dBm)\n"
    }

    fn to_csv_row(&self) -> String {
        format!("{},{:.6},{:.6}\n", self.timestamp, self.percentage, self.power)
    }
}

impl fmt::Display for RssiMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "{:>8} us {:>8.3} % {:>8.3} dBm", self.timestamp, self.percentage, self.power)
    }
}
