// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

use crate::data_messages::*;
use crate::receive_error::*;
use std::fmt;
use std::mem::size_of;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct SyncMessage {
    pub timestamp: u64,
    pub edge: f32,
}

impl Default for SyncMessage {
    fn default() -> Self {
        Self {
            timestamp: 0,
            edge: 0.0,
        }
    }
}

impl DataMessage for SyncMessage {
    fn get_ascii_id() -> u8 {
        b'Y'
    }

    fn parse_ascii(message: &str) -> Result<Self, ReceiveError> {
        match scan_fmt!(message, "{},{d},{f}\n", char, u64, f32) {
            Ok((_, timestamp, edge)) => Ok(Self {
                timestamp,
                edge,
            }),
            Err(_) => Err(ReceiveError::UnableToParseAsciiMessage),
        }
    }

    fn parse_binary(message: &[u8]) -> Result<Self, ReceiveError> {
        #[repr(C, packed)]
        struct BinaryMessage {
            _id: u8,
            timestamp: u64,
            edge: f32,
            _termination: u8,
        }

        if message.len() != size_of::<BinaryMessage>() {
            return Err(ReceiveError::InvalidBinaryMessageLength);
        }

        let binary_message = unsafe {
            let ref binary_message = *(message.as_ptr() as *const BinaryMessage);
            binary_message
        };

        Ok(Self {
            timestamp: binary_message.timestamp,
            edge: binary_message.edge,
        })
    }

    fn get_csv_file_name(&self) -> &'static str {
        "Sync.csv"
    }

    fn get_csv_headings(&self) -> &'static str {
        "Timestamp (us),Edge\n"
    }

    fn to_csv_row(&self) -> String {
        format!("{},{:.6}\n", self.timestamp, self.edge)
    }
}

impl fmt::Display for SyncMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "{:>8} us {:>8.3}", self.timestamp, self.edge)
    }
}
