// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef AHRS_STATUS_MESSAGE_H
#define AHRS_STATUS_MESSAGE_H

#include "../../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_AhrsStatusMessage wrapped;
} AhrsStatusMessage;

static void ahrs_status_message_free(AhrsStatusMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *ahrs_status_message_str(AhrsStatusMessage *self) {
    const char *const string = XIMU3_ahrs_status_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *ahrs_status_message_get_timestamp(AhrsStatusMessage *self, PyObject *args) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *ahrs_status_message_get_string(AhrsStatusMessage *self, PyObject *args) {
    return PyUnicode_FromString(self->wrapped.char_array);
}

static PyObject *ahrs_status_message_get_bytes(AhrsStatusMessage *self, PyObject *args) {
    return PyByteArray_FromStringAndSize(self->wrapped.char_array, (Py_ssize_t) self->wrapped.number_of_bytes);
}

static PyGetSetDef ahrs_status_message_get_set[] = {
    {"timestamp", (getter) ahrs_status_message_get_timestamp, NULL, "", NULL},
    {"string", (getter) ahrs_status_message_get_string, NULL, "", NULL},
    {"bytes", (getter) ahrs_status_message_get_bytes, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyTypeObject ahrs_status_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.AhrsStatusMessage",
    .tp_basicsize = sizeof(AhrsStatusMessage),
    .tp_dealloc = (destructor) ahrs_status_message_free,
    .tp_str = (reprfunc) ahrs_status_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = ahrs_status_message_get_set,
};

static PyObject *ahrs_status_message_from(const XIMU3_AhrsStatusMessage *const message) {
    AhrsStatusMessage *const self = (AhrsStatusMessage *) ahrs_status_message_object.tp_alloc(&ahrs_status_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void ahrs_status_message_callback(XIMU3_AhrsStatusMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = ahrs_status_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
