// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef EARTH_ACCELERATION_MESSAGE_H
#define EARTH_ACCELERATION_MESSAGE_H

#include "../../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_EarthAccelerationMessage wrapped;
} EarthAccelerationMessage;

static void earth_acceleration_message_free(EarthAccelerationMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *earth_acceleration_message_str(EarthAccelerationMessage *self) {
    const char *const string = XIMU3_earth_acceleration_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *earth_acceleration_message_get_timestamp(EarthAccelerationMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *earth_acceleration_message_get_x(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.x);
}

static PyObject *earth_acceleration_message_get_y(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.y);
}

static PyObject *earth_acceleration_message_get_z(EarthAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.z);
}

static PyGetSetDef earth_acceleration_message_get_set[] = {
    {"timestamp", (getter) earth_acceleration_message_get_timestamp, NULL, "", NULL},
    {"x", (getter) earth_acceleration_message_get_x, NULL, "", NULL},
    {"y", (getter) earth_acceleration_message_get_y, NULL, "", NULL},
    {"z", (getter) earth_acceleration_message_get_z, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyTypeObject earth_acceleration_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.EarthAccelerationMessage",
    .tp_basicsize = sizeof(EarthAccelerationMessage),
    .tp_dealloc = (destructor) earth_acceleration_message_free,
    .tp_str = (reprfunc) earth_acceleration_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = earth_acceleration_message_get_set,
};

static PyObject *earth_acceleration_message_from(const XIMU3_EarthAccelerationMessage *const message) {
    EarthAccelerationMessage *const self = (EarthAccelerationMessage *) earth_acceleration_message_object.tp_alloc(&earth_acceleration_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void earth_acceleration_message_callback(XIMU3_EarthAccelerationMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = earth_acceleration_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
