// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#ifndef LINEAR_ACCELERATION_MESSAGE_H
#define LINEAR_ACCELERATION_MESSAGE_H

#include "../../../../C/Ximu3.h"
#include <Python.h>

typedef struct {
    PyObject_HEAD
    XIMU3_LinearAccelerationMessage wrapped;
} LinearAccelerationMessage;

static void linear_acceleration_message_free(LinearAccelerationMessage *self) {
    Py_TYPE(self)->tp_free(self);
}

static PyObject *linear_acceleration_message_str(LinearAccelerationMessage *self) {
    const char *const string = XIMU3_linear_acceleration_message_to_string(self->wrapped);

    return PyUnicode_FromString(string);
}

static PyObject *linear_acceleration_message_get_timestamp(LinearAccelerationMessage *self) {
    return PyLong_FromUnsignedLongLong((unsigned long long) self->wrapped.timestamp);
}

static PyObject *linear_acceleration_message_get_x(LinearAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.x);
}

static PyObject *linear_acceleration_message_get_y(LinearAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.y);
}

static PyObject *linear_acceleration_message_get_z(LinearAccelerationMessage *self) {
    return PyFloat_FromDouble((double) self->wrapped.z);
}

static PyGetSetDef linear_acceleration_message_get_set[] = {
    {"timestamp", (getter) linear_acceleration_message_get_timestamp, NULL, "", NULL},
    {"x", (getter) linear_acceleration_message_get_x, NULL, "", NULL},
    {"y", (getter) linear_acceleration_message_get_y, NULL, "", NULL},
    {"z", (getter) linear_acceleration_message_get_z, NULL, "", NULL},
    {NULL} /* sentinel */
};

static PyTypeObject linear_acceleration_message_object = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "ximu3.LinearAccelerationMessage",
    .tp_basicsize = sizeof(LinearAccelerationMessage),
    .tp_dealloc = (destructor) linear_acceleration_message_free,
    .tp_str = (reprfunc) linear_acceleration_message_str,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_getset = linear_acceleration_message_get_set,
};

static PyObject *linear_acceleration_message_from(const XIMU3_LinearAccelerationMessage *const message) {
    LinearAccelerationMessage *const self = (LinearAccelerationMessage *) linear_acceleration_message_object.tp_alloc(&linear_acceleration_message_object, 0);

    if (self == NULL) {
        return NULL;
    }

    self->wrapped = *message;
    return (PyObject *) self;
}

static void linear_acceleration_message_callback(XIMU3_LinearAccelerationMessage data, void *context) {
    PyObject *object = NULL;
    PyObject *tuple = NULL;
    PyObject *result = NULL;

    const PyGILState_STATE state = PyGILState_Ensure();

    object = linear_acceleration_message_from(&data);

    if (object == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    tuple = PyTuple_Pack(1, object);

    if (tuple == NULL) {
        PyErr_Print();
        goto cleanup;
    }

    result = PyObject_CallObject((PyObject *) context, tuple);

    if (result == NULL) {
        PyErr_Print();
    }

cleanup:
    Py_XDECREF(object);
    Py_XDECREF(tuple);
    Py_XDECREF(result);

    PyGILState_Release(state);
}

#endif
