// This file was generated by Examples/Cpp/generate_main.py

#include "Examples/BluetoothConnection.h"
#include "Examples/Commands.h"
#include "Examples/DataLogger.h"
#include "Examples/FileConverter.h"
#include "Examples/GetPortNames.h"
#include "Examples/NetworkAnnouncement.h"
#include "Examples/OpenAndPing.h"
#include "Examples/PortScanner.h"
#include "Examples/SerialConnection.h"
#include "Examples/TcpConnection.h"
#include "Examples/UdpConnection.h"
#include "Examples/UsbConnection.h"
#include "Helpers.hpp"
#include <iostream>

int main(int argc, const char* argv[])
{
    setbuf(stdout, NULL);
    std::cout << "Select example " << std::endl;
    std::cout << "A. BluetoothConnection.h" << std::endl;
    std::cout << "B. Commands.h" << std::endl;
    std::cout << "C. DataLogger.h" << std::endl;
    std::cout << "D. FileConverter.h" << std::endl;
    std::cout << "E. GetPortNames.h" << std::endl;
    std::cout << "F. NetworkAnnouncement.h" << std::endl;
    std::cout << "G. OpenAndPing.h" << std::endl;
    std::cout << "H. PortScanner.h" << std::endl;
    std::cout << "I. SerialConnection.h" << std::endl;
    std::cout << "J. TcpConnection.h" << std::endl;
    std::cout << "K. UdpConnection.h" << std::endl;
    std::cout << "L. UsbConnection.h" << std::endl;
    switch (helpers::getKey())
    {
        case 'A':
            BluetoothConnection();
            break;
        case 'B':
            Commands();
            break;
        case 'C':
            DataLogger();
            break;
        case 'D':
            FileConverter();
            break;
        case 'E':
            GetPortNames();
            break;
        case 'F':
            NetworkAnnouncement();
            break;
        case 'G':
            OpenAndPing();
            break;
        case 'H':
            PortScanner();
            break;
        case 'I':
            SerialConnection();
            break;
        case 'J':
            TcpConnection();
            break;
        case 'K':
            UdpConnection();
            break;
        case 'L':
            UsbConnection();
            break;
    }
}
