// This file was generated by Examples/Cpp/generate_main.py

#include "Examples/BluetoothConnection.h"
#include "Examples/Commands.h"
#include "Examples/DataLogger.h"
#include "Examples/FileConnection.h"
#include "Examples/FileConverter.h"
#include "Examples/GetPortNames.h"
#include "Examples/KeepOpen.h"
#include "Examples/NetworkAnnouncement.h"
#include "Examples/OpenAsync.h"
#include "Examples/Ping.h"
#include "Examples/PortScanner.h"
#include "Examples/SerialConnection.h"
#include "Examples/TcpConnection.h"
#include "Examples/UdpConnection.h"
#include "Examples/UsbConnection.h"
#include "Helpers.hpp"
#include <iostream>

int main(int argc, const char* argv[])
{
    setbuf(stdout, NULL);

    std::cout << "Select example " << std::endl;
    std::cout << "A. BluetoothConnection.h" << std::endl;
    std::cout << "B. Commands.h" << std::endl;
    std::cout << "C. DataLogger.h" << std::endl;
    std::cout << "D. FileConnection.h" << std::endl;
    std::cout << "E. FileConverter.h" << std::endl;
    std::cout << "F. GetPortNames.h" << std::endl;
    std::cout << "G. KeepOpen.h" << std::endl;
    std::cout << "H. NetworkAnnouncement.h" << std::endl;
    std::cout << "I. OpenAsync.h" << std::endl;
    std::cout << "J. Ping.h" << std::endl;
    std::cout << "K. PortScanner.h" << std::endl;
    std::cout << "L. SerialConnection.h" << std::endl;
    std::cout << "M. TcpConnection.h" << std::endl;
    std::cout << "N. UdpConnection.h" << std::endl;
    std::cout << "O. UsbConnection.h" << std::endl;

    switch (helpers::getKey())
    {
        case 'A':
            BluetoothConnection();
            break;
        case 'B':
            Commands();
            break;
        case 'C':
            DataLogger();
            break;
        case 'D':
            FileConnection();
            break;
        case 'E':
            FileConverter();
            break;
        case 'F':
            GetPortNames();
            break;
        case 'G':
            KeepOpen();
            break;
        case 'H':
            NetworkAnnouncement();
            break;
        case 'I':
            OpenAsync();
            break;
        case 'J':
            Ping();
            break;
        case 'K':
            PortScanner();
            break;
        case 'L':
            SerialConnection();
            break;
        case 'M':
            TcpConnection();
            break;
        case 'N':
            UdpConnection();
            break;
        case 'O':
            UsbConnection();
            break;
    }
}
