// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class BatteryMessage
    {
    internal:
        BatteryMessage(ximu3::XIMU3_BatteryMessage message) : message{ new ximu3::XIMU3_BatteryMessage{message} }
        {
        }

    public:
        ~BatteryMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float Percentage
        {
            float get()
            {
                return message->percentage;
            }
        }

        property float Voltage
        {
            float get()
            {
                return message->voltage;
            }
        }

        property float ChargingStatus
        {
            float get()
            {
                return message->charging_status;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_battery_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_BatteryMessage* message;
    };
}
