// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class EulerAnglesMessage
    {
    internal:
        EulerAnglesMessage(ximu3::XIMU3_EulerAnglesMessage message) : message{ new ximu3::XIMU3_EulerAnglesMessage{message} }
        {
        }

    public:
        ~EulerAnglesMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float Roll
        {
            float get()
            {
                return message->roll;
            }
        }

        property float Pitch
        {
            float get()
            {
                return message->pitch;
            }
        }

        property float Yaw
        {
            float get()
            {
                return message->yaw;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_euler_angles_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_EulerAnglesMessage* message;
    };
}
