// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class InertialMessage
    {
    internal:
        InertialMessage(ximu3::XIMU3_InertialMessage message) : message{ new ximu3::XIMU3_InertialMessage{message} }
        {
        }

    public:
        ~InertialMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float GyroscopeX
        {
            float get()
            {
                return message->gyroscope_x;
            }
        }

        property float GyroscopeY
        {
            float get()
            {
                return message->gyroscope_y;
            }
        }

        property float GyroscopeZ
        {
            float get()
            {
                return message->gyroscope_z;
            }
        }

        property float AccelerometerX
        {
            float get()
            {
                return message->accelerometer_x;
            }
        }

        property float AccelerometerY
        {
            float get()
            {
                return message->accelerometer_y;
            }
        }

        property float AccelerometerZ
        {
            float get()
            {
                return message->accelerometer_z;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_inertial_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_InertialMessage* message;
    };
}
