// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class LinearAccelerationMessage
    {
    internal:
        LinearAccelerationMessage(ximu3::XIMU3_LinearAccelerationMessage message) : message{ new ximu3::XIMU3_LinearAccelerationMessage{message} }
        {
        }

    public:
        ~LinearAccelerationMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float QuaternionW
        {
            float get()
            {
                return message->quaternion_w;
            }
        }

        property float QuaternionX
        {
            float get()
            {
                return message->quaternion_x;
            }
        }

        property float QuaternionY
        {
            float get()
            {
                return message->quaternion_y;
            }
        }

        property float QuaternionZ
        {
            float get()
            {
                return message->quaternion_z;
            }
        }

        property float AccelerationX
        {
            float get()
            {
                return message->acceleration_x;
            }
        }

        property float AccelerationY
        {
            float get()
            {
                return message->acceleration_y;
            }
        }

        property float AccelerationZ
        {
            float get()
            {
                return message->acceleration_z;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_linear_acceleration_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_LinearAccelerationMessage* message;
    };
}
