// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class MagnetometerMessage
    {
    internal:
        MagnetometerMessage(ximu3::XIMU3_MagnetometerMessage message) : message{ new ximu3::XIMU3_MagnetometerMessage{message} }
        {
        }

    public:
        ~MagnetometerMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float XAxis
        {
            float get()
            {
                return message->x_axis;
            }
        }

        property float YAxis
        {
            float get()
            {
                return message->y_axis;
            }
        }

        property float ZAxis
        {
            float get()
            {
                return message->z_axis;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_magnetometer_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_MagnetometerMessage* message;
    };
}
