// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class RotationMatrixMessage
    {
    internal:
        RotationMatrixMessage(ximu3::XIMU3_RotationMatrixMessage message) : message{ new ximu3::XIMU3_RotationMatrixMessage{message} }
        {
        }

    public:
        ~RotationMatrixMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float XXElement
        {
            float get()
            {
                return message->xx_element;
            }
        }

        property float XYElement
        {
            float get()
            {
                return message->xy_element;
            }
        }

        property float XZElement
        {
            float get()
            {
                return message->xz_element;
            }
        }

        property float YXElement
        {
            float get()
            {
                return message->yx_element;
            }
        }

        property float YYElement
        {
            float get()
            {
                return message->yy_element;
            }
        }

        property float YZElement
        {
            float get()
            {
                return message->yz_element;
            }
        }

        property float ZXElement
        {
            float get()
            {
                return message->zx_element;
            }
        }

        property float ZYElement
        {
            float get()
            {
                return message->zy_element;
            }
        }

        property float ZZElement
        {
            float get()
            {
                return message->zz_element;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_rotation_matrix_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_RotationMatrixMessage* message;
    };
}
