// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class RotationMatrixMessage
    {
    internal:
        RotationMatrixMessage(ximu3::XIMU3_RotationMatrixMessage message) : message{ new ximu3::XIMU3_RotationMatrixMessage{message} }
        {
        }

    public:
        ~RotationMatrixMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float XX
        {
            float get()
            {
                return message->xx;
            }
        }

        property float XY
        {
            float get()
            {
                return message->xy;
            }
        }

        property float XZ
        {
            float get()
            {
                return message->xz;
            }
        }

        property float YX
        {
            float get()
            {
                return message->yx;
            }
        }

        property float YY
        {
            float get()
            {
                return message->yy;
            }
        }

        property float YZ
        {
            float get()
            {
                return message->yz;
            }
        }

        property float ZX
        {
            float get()
            {
                return message->zx;
            }
        }

        property float ZY
        {
            float get()
            {
                return message->zy;
            }
        }

        property float ZZ
        {
            float get()
            {
                return message->zz;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_rotation_matrix_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_RotationMatrixMessage* message;
    };
}
