// This file was generated by x-IMU3-API/Rust/src/data_messages/generate_data_messages.py

#pragma once

#include "../../../C/Ximu3.h"

using namespace System;

namespace Ximu3
{
    public ref class TemperatureMessage
    {
    internal:
        TemperatureMessage(ximu3::XIMU3_TemperatureMessage message) : message{ new ximu3::XIMU3_TemperatureMessage{message} }
        {
        }

    public:
        ~TemperatureMessage()
        {
            delete message;
        }

        property UInt64 Timestamp
        {
            UInt64 get()
            {
                return message->timestamp;
            }
        }

        property float Temperature
        {
            float get()
            {
                return message->temperature;
            }
        }

        String^ ToString() override
        {
            return gcnew String(ximu3::XIMU3_temperature_message_to_string(*message));
        }

    private:
        ximu3::XIMU3_TemperatureMessage* message;
    };
}
