// This file was generated by Examples/CSharp/x-IMU3-Examples/generate_main.py

namespace Ximu3Examples
{
    class Program
    {
        static int Main()
        {
            Console.WriteLine("Select example");
            Console.WriteLine("A. BluetoothConnection");
            Console.WriteLine("B. Commands");
            Console.WriteLine("C. DataLogger");
            Console.WriteLine("D. FileConnection");
            Console.WriteLine("E. FileConverter");
            Console.WriteLine("F. GetPortNames");
            Console.WriteLine("G. NetworkAnnouncement");
            Console.WriteLine("H. OpenAsync");
            Console.WriteLine("I. Ping");
            Console.WriteLine("J. PortScanner");
            Console.WriteLine("K. SerialConnection");
            Console.WriteLine("L. TcpConnection");
            Console.WriteLine("M. UdpConnection");
            Console.WriteLine("N. UsbConnection");

            switch (Helpers.GetKey())
            {
                case 'A':
                    _ = new BluetoothConnection();
                    break;
                case 'B':
                    _ = new Commands();
                    break;
                case 'C':
                    _ = new DataLogger();
                    break;
                case 'D':
                    _ = new FileConnection();
                    break;
                case 'E':
                    _ = new FileConverter();
                    break;
                case 'F':
                    _ = new GetPortNames();
                    break;
                case 'G':
                    _ = new NetworkAnnouncement();
                    break;
                case 'H':
                    _ = new OpenAsync();
                    break;
                case 'I':
                    _ = new Ping();
                    break;
                case 'J':
                    _ = new PortScanner();
                    break;
                case 'K':
                    _ = new SerialConnection();
                    break;
                case 'L':
                    _ = new TcpConnection();
                    break;
                case 'M':
                    _ = new UdpConnection();
                    break;
                case 'N':
                    _ = new UsbConnection();
                    break;
            }

            Console.WriteLine("Press any key to exit");
            Helpers.GetKey();
            return 0;
        }
    }
}
