// This file was generated by Examples/CSharp/x-IMU3-Examples/generate_program.py

namespace Ximu3Examples
{
    class Program
    {
        static int Main()
        {
            Console.WriteLine("Select example");
            Console.WriteLine("A. BluetoothConnection");
            Console.WriteLine("B. DataLogger");
            Console.WriteLine("C. FileConnection");
            Console.WriteLine("D. FileConverter");
            Console.WriteLine("E. GetPortNames");
            Console.WriteLine("F. KeepOpen");
            Console.WriteLine("G. MuxConnection");
            Console.WriteLine("H. MuxScanner");
            Console.WriteLine("I. NetworkAnnouncement");
            Console.WriteLine("J. OpenAsync");
            Console.WriteLine("K. Ping");
            Console.WriteLine("L. PortScanner");
            Console.WriteLine("M. SendCommands");
            Console.WriteLine("N. SerialConnection");
            Console.WriteLine("O. TcpConnection");
            Console.WriteLine("P. UdpConnection");
            Console.WriteLine("Q. UsbConnection");

            switch (Helpers.GetKey())
            {
                case 'A':
                    _ = new BluetoothConnection();
                    break;
                case 'B':
                    _ = new DataLogger();
                    break;
                case 'C':
                    _ = new FileConnection();
                    break;
                case 'D':
                    _ = new FileConverter();
                    break;
                case 'E':
                    _ = new GetPortNames();
                    break;
                case 'F':
                    _ = new KeepOpen();
                    break;
                case 'G':
                    _ = new MuxConnection();
                    break;
                case 'H':
                    _ = new MuxScanner();
                    break;
                case 'I':
                    _ = new NetworkAnnouncement();
                    break;
                case 'J':
                    _ = new OpenAsync();
                    break;
                case 'K':
                    _ = new Ping();
                    break;
                case 'L':
                    _ = new PortScanner();
                    break;
                case 'M':
                    _ = new SendCommands();
                    break;
                case 'N':
                    _ = new SerialConnection();
                    break;
                case 'O':
                    _ = new TcpConnection();
                    break;
                case 'P':
                    _ = new UdpConnection();
                    break;
                case 'Q':
                    _ = new UsbConnection();
                    break;
            }

            return 0;
        }
    }
}
